/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.city_id_seq</code>
     */
    public static final Sequence<Long> CITY_ID_SEQ = new SequenceImpl<Long>("city_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.examination_id_seq</code>
     */
    public static final Sequence<Long> EXAMINATION_ID_SEQ = new SequenceImpl<Long>("examination_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.follows_id_seq</code>
     */
    public static final Sequence<Long> FOLLOWS_ID_SEQ = new SequenceImpl<Long>("follows_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.medicine_id_seq</code>
     */
    public static final Sequence<Long> MEDICINE_ID_SEQ = new SequenceImpl<Long>("medicine_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.person_id_seq</code>
     */
    public static final Sequence<Long> PERSON_ID_SEQ = new SequenceImpl<Long>("person_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.prescription_id_seq</code>
     */
    public static final Sequence<Long> PRESCRIPTION_ID_SEQ = new SequenceImpl<Long>("prescription_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.province_id_seq</code>
     */
    public static final Sequence<Long> PROVINCE_ID_SEQ = new SequenceImpl<Long>("province_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.region_id_seq</code>
     */
    public static final Sequence<Long> REGION_ID_SEQ = new SequenceImpl<Long>("region_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
