/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq;


import dunder.mifflin.persistence.jdbc.jooq.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.avatar</code>.
     */
    public static final Avatar AVATAR = Avatar.AVATAR;

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>public.examination</code>.
     */
    public static final Examination EXAMINATION = Examination.EXAMINATION;

    /**
     * The table <code>public.follows</code>.
     */
    public static final Follows FOLLOWS = Follows.FOLLOWS;

    /**
     * The table <code>public.general</code>.
     */
    public static final General GENERAL = General.GENERAL;

    /**
     * The table <code>public.hs_admin</code>.
     */
    public static final HsAdmin HS_ADMIN = HsAdmin.HS_ADMIN;

    /**
     * The table <code>public.hs_doctor</code>.
     */
    public static final HsDoctor HS_DOCTOR = HsDoctor.HS_DOCTOR;

    /**
     * The table <code>public.hs_exam</code>.
     */
    public static final HsExam HS_EXAM = HsExam.HS_EXAM;

    /**
     * The table <code>public.hs_prescription</code>.
     */
    public static final HsPrescription HS_PRESCRIPTION = HsPrescription.HS_PRESCRIPTION;

    /**
     * The table <code>public.hs_qualification</code>.
     */
    public static final HsQualification HS_QUALIFICATION = HsQualification.HS_QUALIFICATION;

    /**
     * The table <code>public.hs_report</code>.
     */
    public static final HsReport HS_REPORT = HsReport.HS_REPORT;

    /**
     * The table <code>public.hs_ticket</code>.
     */
    public static final HsTicket HS_TICKET = HsTicket.HS_TICKET;

    /**
     * The table <code>public.medicine</code>.
     */
    public static final Medicine MEDICINE = Medicine.MEDICINE;

    /**
     * The table <code>public.medicine_prescription</code>.
     */
    public static final MedicinePrescription MEDICINE_PRESCRIPTION = MedicinePrescription.MEDICINE_PRESCRIPTION;

    /**
     * The table <code>public.medicine_ticket</code>.
     */
    public static final MedicineTicket MEDICINE_TICKET = MedicineTicket.MEDICINE_TICKET;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>public.prescription</code>.
     */
    public static final Prescription PRESCRIPTION = Prescription.PRESCRIPTION;

    /**
     * The table <code>public.province</code>.
     */
    public static final Province PROVINCE = Province.PROVINCE;

    /**
     * The table <code>public.region</code>.
     */
    public static final Region REGION = Region.REGION;

    /**
     * The table <code>public.sp_exam</code>.
     */
    public static final SpExam SP_EXAM = SpExam.SP_EXAM;

    /**
     * The table <code>public.sp_prescription</code>.
     */
    public static final SpPrescription SP_PRESCRIPTION = SpPrescription.SP_PRESCRIPTION;

    /**
     * The table <code>public.sp_qualification</code>.
     */
    public static final SpQualification SP_QUALIFICATION = SpQualification.SP_QUALIFICATION;

    /**
     * The table <code>public.sp_report</code>.
     */
    public static final SpReport SP_REPORT = SpReport.SP_REPORT;

    /**
     * The table <code>public.sp_ticket</code>.
     */
    public static final SpTicket SP_TICKET = SpTicket.SP_TICKET;

    /**
     * The table <code>public.specialist</code>.
     */
    public static final Specialist SPECIALIST = Specialist.SPECIALIST;

    /**
     * The table <code>public.token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;
}
