/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq.tables;


import dunder.mifflin.persistance.jdbc.jooq.Indexes;
import dunder.mifflin.persistance.jdbc.jooq.Keys;
import dunder.mifflin.persistance.jdbc.jooq.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HsExam extends TableImpl<Record> {

    private static final long serialVersionUID = 652523027;

    /**
     * The reference instance of <code>public.hs_exam</code>
     */
    public static final HsExam HS_EXAM = new HsExam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.hs_exam.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.hs_exam</code> table reference
     */
    public HsExam() {
        this(DSL.name("hs_exam"), null);
    }

    /**
     * Create an aliased <code>public.hs_exam</code> table reference
     */
    public HsExam(String alias) {
        this(DSL.name(alias), HS_EXAM);
    }

    /**
     * Create an aliased <code>public.hs_exam</code> table reference
     */
    public HsExam(Name alias) {
        this(alias, HS_EXAM);
    }

    private HsExam(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private HsExam(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HsExam(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, HS_EXAM);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HS_EXAM_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.HS_EXAM_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.HS_EXAM_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.HS_EXAM__HS_EXAM_ID_FKEY);
    }

    public Examination examination() {
        return new Examination(this, Keys.HS_EXAM__HS_EXAM_ID_FKEY);
    }

    @Override
    public HsExam as(String alias) {
        return new HsExam(DSL.name(alias), this);
    }

    @Override
    public HsExam as(Name alias) {
        return new HsExam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HsExam rename(String name) {
        return new HsExam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HsExam rename(Name name) {
        return new HsExam(name, null);
    }
}
