/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq.tables;


import dunder.mifflin.persistance.jdbc.jooq.Indexes;
import dunder.mifflin.persistance.jdbc.jooq.Keys;
import dunder.mifflin.persistance.jdbc.jooq.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HsQualification extends TableImpl<Record> {

    private static final long serialVersionUID = -208160858;

    /**
     * The reference instance of <code>public.hs_qualification</code>
     */
    public static final HsQualification HS_QUALIFICATION = new HsQualification();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.hs_qualification.doctor</code>.
     */
    public final TableField<Record, Long> DOCTOR = createField(DSL.name("doctor"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.hs_qualification.exam</code>.
     */
    public final TableField<Record, Long> EXAM = createField(DSL.name("exam"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.hs_qualification</code> table reference
     */
    public HsQualification() {
        this(DSL.name("hs_qualification"), null);
    }

    /**
     * Create an aliased <code>public.hs_qualification</code> table reference
     */
    public HsQualification(String alias) {
        this(DSL.name(alias), HS_QUALIFICATION);
    }

    /**
     * Create an aliased <code>public.hs_qualification</code> table reference
     */
    public HsQualification(Name alias) {
        this(alias, HS_QUALIFICATION);
    }

    private HsQualification(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private HsQualification(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HsQualification(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, HS_QUALIFICATION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HS_QUALIFICATION_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.HS_QUALIFICATION_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.HS_QUALIFICATION_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.HS_QUALIFICATION__HS_QUALIFICATION_DOCTOR_FKEY, Keys.HS_QUALIFICATION__HS_QUALIFICATION_EXAM_FKEY);
    }

    public HsDoctor hsDoctor() {
        return new HsDoctor(this, Keys.HS_QUALIFICATION__HS_QUALIFICATION_DOCTOR_FKEY);
    }

    public HsExam hsExam() {
        return new HsExam(this, Keys.HS_QUALIFICATION__HS_QUALIFICATION_EXAM_FKEY);
    }

    @Override
    public HsQualification as(String alias) {
        return new HsQualification(DSL.name(alias), this);
    }

    @Override
    public HsQualification as(Name alias) {
        return new HsQualification(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HsQualification rename(String name) {
        return new HsQualification(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HsQualification rename(Name name) {
        return new HsQualification(name, null);
    }
}
