/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq.tables;


import dunder.mifflin.persistance.jdbc.jooq.Indexes;
import dunder.mifflin.persistance.jdbc.jooq.Keys;
import dunder.mifflin.persistance.jdbc.jooq.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrMedicine extends TableImpl<Record> {

    private static final long serialVersionUID = 1488493593;

    /**
     * The reference instance of <code>public.pr_medicine</code>
     */
    public static final PrMedicine PR_MEDICINE = new PrMedicine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.pr_medicine.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pr_medicine.medicine</code>.
     */
    public final TableField<Record, Long> MEDICINE = createField(DSL.name("medicine"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pr_medicine.quantity</code>.
     */
    public final TableField<Record, Integer> QUANTITY = createField(DSL.name("quantity"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.pr_medicine</code> table reference
     */
    public PrMedicine() {
        this(DSL.name("pr_medicine"), null);
    }

    /**
     * Create an aliased <code>public.pr_medicine</code> table reference
     */
    public PrMedicine(String alias) {
        this(DSL.name(alias), PR_MEDICINE);
    }

    /**
     * Create an aliased <code>public.pr_medicine</code> table reference
     */
    public PrMedicine(Name alias) {
        this(alias, PR_MEDICINE);
    }

    private PrMedicine(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PrMedicine(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PrMedicine(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, PR_MEDICINE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PR_MEDICINE_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PR_MEDICINE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PR_MEDICINE_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.PR_MEDICINE__PR_MEDICINE_PRESCRIPTION_FKEY, Keys.PR_MEDICINE__PR_MEDICINE_MEDICINE_FKEY);
    }

    public Prescription prescription() {
        return new Prescription(this, Keys.PR_MEDICINE__PR_MEDICINE_PRESCRIPTION_FKEY);
    }

    public Medicine medicine() {
        return new Medicine(this, Keys.PR_MEDICINE__PR_MEDICINE_MEDICINE_FKEY);
    }

    @Override
    public PrMedicine as(String alias) {
        return new PrMedicine(DSL.name(alias), this);
    }

    @Override
    public PrMedicine as(Name alias) {
        return new PrMedicine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PrMedicine rename(String name) {
        return new PrMedicine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrMedicine rename(Name name) {
        return new PrMedicine(name, null);
    }
}
