/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq.tables;


import dunder.mifflin.persistance.jdbc.jooq.Indexes;
import dunder.mifflin.persistance.jdbc.jooq.Keys;
import dunder.mifflin.persistance.jdbc.jooq.Public;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recover extends TableImpl<Record> {

    private static final long serialVersionUID = -1207058593;

    /**
     * The reference instance of <code>public.recover</code>
     */
    public static final Recover RECOVER = new Recover();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.recover.person</code>.
     */
    public final TableField<Record, Long> PERSON = createField(DSL.name("person"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.recover.token</code>.
     */
    public final TableField<Record, UUID> TOKEN = createField(DSL.name("token"), org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("uuid_generate_v4()", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.recover.expiration</code>.
     */
    public final TableField<Record, OffsetDateTime> EXPIRATION = createField(DSL.name("expiration"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("(CURRENT_TIMESTAMP + '02:00:00'::interval)", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * Create a <code>public.recover</code> table reference
     */
    public Recover() {
        this(DSL.name("recover"), null);
    }

    /**
     * Create an aliased <code>public.recover</code> table reference
     */
    public Recover(String alias) {
        this(DSL.name(alias), RECOVER);
    }

    /**
     * Create an aliased <code>public.recover</code> table reference
     */
    public Recover(Name alias) {
        this(alias, RECOVER);
    }

    private Recover(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Recover(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Recover(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, RECOVER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RECOVER_PKEY, Indexes.RECOVER_TOKEN_KEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.RECOVER_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.RECOVER_PKEY, Keys.RECOVER_TOKEN_KEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.RECOVER__RECOVER_PERSON_FKEY);
    }

    public Person person() {
        return new Person(this, Keys.RECOVER__RECOVER_PERSON_FKEY);
    }

    @Override
    public Recover as(String alias) {
        return new Recover(DSL.name(alias), this);
    }

    @Override
    public Recover as(Name alias) {
        return new Recover(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Recover rename(String name) {
        return new Recover(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Recover rename(Name name) {
        return new Recover(name, null);
    }
}
