/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq.tables;


import dunder.mifflin.persistance.jdbc.jooq.Indexes;
import dunder.mifflin.persistance.jdbc.jooq.Keys;
import dunder.mifflin.persistance.jdbc.jooq.Public;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpReport extends TableImpl<Record> {

    private static final long serialVersionUID = 1211100266;

    /**
     * The reference instance of <code>public.sp_report</code>
     */
    public static final SpReport SP_REPORT = new SpReport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.sp_report.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sp_report.specialist</code>.
     */
    public final TableField<Record, Long> SPECIALIST = createField(DSL.name("specialist"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sp_report.date</code>.
     */
    public final TableField<Record, OffsetDateTime> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.sp_report.note</code>.
     */
    public final TableField<Record, String> NOTE = createField(DSL.name("note"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.sp_report</code> table reference
     */
    public SpReport() {
        this(DSL.name("sp_report"), null);
    }

    /**
     * Create an aliased <code>public.sp_report</code> table reference
     */
    public SpReport(String alias) {
        this(DSL.name(alias), SP_REPORT);
    }

    /**
     * Create an aliased <code>public.sp_report</code> table reference
     */
    public SpReport(Name alias) {
        this(alias, SP_REPORT);
    }

    private SpReport(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private SpReport(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SpReport(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, SP_REPORT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SP_REPORT_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.SP_REPORT_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.SP_REPORT_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.SP_REPORT__SP_REPORT_PRESCRIPTION_FKEY, Keys.SP_REPORT__SP_REPORT_SPECIALIST_FKEY);
    }

    public PrSpExam prSpExam() {
        return new PrSpExam(this, Keys.SP_REPORT__SP_REPORT_PRESCRIPTION_FKEY);
    }

    public Specialist specialist() {
        return new Specialist(this, Keys.SP_REPORT__SP_REPORT_SPECIALIST_FKEY);
    }

    @Override
    public SpReport as(String alias) {
        return new SpReport(DSL.name(alias), this);
    }

    @Override
    public SpReport as(Name alias) {
        return new SpReport(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpReport rename(String name) {
        return new SpReport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpReport rename(Name name) {
        return new SpReport(name, null);
    }
}
