INSERT INTO examination(name, info)
VALUES ('Estrazione di dente deciduo', 'Info Estrazione di dente deciduo (gratuita fino a 14 anni)'),
       ('Estrazione di dente permanente', 'Info Estrazione di dente permanente (gratuita fino a 14 anni)'),
       ('Altra estrazione chirurgica dente', 'Info Altra estrazione chirurgica dente (gratuita fino a 14 anni)'),
       ('Ricostruzione dente con otturazione',
        'Info Ricostruzione dente con otturazione (gratuita fino a 14 anni solo in caso di evento traumatico)'),
       ('Ricostruzione dente mediante otturazione a tre o più superfici',
        'Info Ricostruzione dente mediante otturazione a tre o più superfici'),
       ('Ricostruzione dente mediante intarsio', 'Info Ricostruzione dente mediante intarsio'),
       ('Applicazione di corona', 'Info Applicazione di corona'),
       ('Applicazione di corona in lega aurea', 'Info Applicazione di corona in lega aurea'),
       ('Altra applicazione corona', 'Info Altra applicazione corona'),
       ('Applicazione corona e perno', 'Info Applicazione corona e perno'),
       ('Altra applicazione corona e perno', 'Info Altra applicazione corona e perno'),
       ('Inserzione di ponte fisso', 'Info Inserzione di ponte fisso'),
       ('Inserzione di protesi rimovibile', 'Info Inserzione di protesi rimovibile'),
       ('Altra inserzione di protesi', 'Info Altra inserzione di protesi'),
       ('Inserzione di protesi provvisoria', 'Info Inserzione di protesi provvisoria'),
       ('Altra riparazione dentaria', 'Info Altra riparazione dentaria'),
       ('Impianto di dente', 'Info Impianto di dente (gratuita fino a 14 anni)'),
       ('Impianto di protesi dentaria', 'Info Impianto di protesi dentaria'),
       ('Terapia canalare in monoradicolato', 'Info Terapia canalare in monoradicolato'),
       ('Terapia canalare in pluriradicolato', 'Info Terapia canalare in pluriradicolato'),
       ('Apicectomia', 'Info Apicectomia'),
       ('Gengivoplastica', 'Info Gengivoplastica'),
       ('Asportazione di tessuto della gengiva',
        'Info Asportazione di tessuto della gengiva (gratuita fino a 14 anni)'),
       ('Levigatura delle radici', 'Info Levigatura delle radici'),
       ('Intervento chirurgico preprotesico', 'Info Intervento chirurgico preprotesico'),
       ('Asportazione di lesione dentaria della mandibola (gratuita fino a 14 anni)',
        'Info Asportazione di lesione dentaria della mandibola (gratuita fino a 14 anni)'),
       ('Trattamento ortodontico con apparecchi mobili', 'Info Trattamento ortodontico con apparecchi mobili'),
       ('Trattamento con apparecchi fissi', 'Info Trattamento con apparecchi fissi'),
       ('Trattamento con apparecchi funzionali', 'Info Trattamento con apparecchi funzionali'),
       ('Riparazione di apparecchio ortodontico', 'Info Riparazione di apparecchio ortodontico'),
       ('Radiologia diagnostica', 'Info Radiologia diagnostica'),
       ('Tomografia computerizzata del rachide', 'Info Tomografia computerizzata del rachide'),
       ('Tomografia computerizzata con contrasto', 'Info Tomografia computerizzata con contrasto'),
       ('Tomografia computerizzata dell''arto superiore (solo con patologia traumatica acuta)',
        'Info Tomografia computerizzata dell''arto superiore (solo con patologia traumatica acuta)'),
       ('Tomografia computerizzata dell''arto superiore senza e con contrasto (patologia o sospetto oncologico)',
        'Info Tomografia computerizzata dell''arto superiore senza e con contrasto (patologia o sospetto oncologico)'),
       ('Tomografia computerizzata dell''arto inferiore (patologia traumatica)',
        'Info Tomografia computerizzata dell''arto inferiore (patologia traumatica)'),
       ('Tomografia computerizzata dell''arto inferiore senza e con contrasto (patologia o sospetto oncologico)',
        'Info Tomografia computerizzata dell''arto inferiore senza e con contrasto (patologia o sospetto oncologico)'),
       ('Risonanza magnetica nucleare (RM) della colonna cervicale',
        'Info Risonanza magnetica nucleare (RM) della colonna cervicale'),
       ('Risonanza magnetica nucleare (RM) della colonna senza e con contrasto',
        'Info Risonanza magnetica nucleare (RM) della colonna senza e con contrasto'),
       ('Tempo di protrombina', 'Info Tempo di protrombina'),
       ('Tempo di tromboplastina', 'Info Tempo di tromboplastina'),
       ('Test aggregazione piastrinica', 'Info Test aggregazione piastrinica'),
       ('Test resistenza proteina C', 'Info Test resistenza proteina C'),
       ('Tipizzazione genomica', 'Info Tipizzazione genomica'),
       ('Tipizzazione genomica HLA : A sequenziamento diretto',
        'Info Tipizzazione genomica HLA : A sequenziamento diretto'),
       ('Tipizzazione genomica HLA : B', 'Info Tipizzazione genomica HLA : B'),
       ('Tipizzazione genomica HLA : B sequenziamento diretto',
        'Info Tipizzazione genomica HLA : B sequenziamento diretto'),
       ('Tipizzazione genomica HLA : C', 'Info Tipizzazione genomica HLA : C'),
       ('Tipizzazione genomica HLA : C seq. diretto', 'Info Tipizzazione genomica HLA : C seq. diretto'),
       ('Tipizzazione genomica HLA : DP seq. diretto', 'Info Tipizzazione genomica HLA : DP seq. diretto'),
       ('Tipizzazione genomica HLA : DP alta risoluzione',
        'Info Tipizzazione genomica HLA : DP alta risoluzione'),
       ('Tipizzazione genomica HLA : DQ seq. diretto', 'Info Tipizzazione genomica HLA : DQ seq. diretto'),
       ('Tipizzazione genomica HLA : DQ alta risoluzione',
        'Info Tipizzazione genomica HLA : DQ alta risoluzione'),
       ('Tipizzazione genomica HLA : DQB1 bassa risoluzione',
        'Info Tipizzazione genomica HLA : DQB1 bassa risoluzione'),
       ('Tipizzazione genomica HLA : DQB1 alta risoluzione',
        'Info Tipizzazione genomica HLA : DQB1 alta risoluzione'),
       ('Tipizzazione genomica HLA : DR seq. diretto', 'Info Tipizzazione genomica HLA : DR seq. diretto'),
       ('Tipizzazione genomica HLA : DRB bassa risoluzione',
        'Info Tipizzazione genomica HLA : DRB bassa risoluzione'),
       ('Tipizzazione genomica HLA : DRB alta risoluzione',
        'Info Tipizzazione genomica HLA : DRB alta risoluzione'),
       ('Tipizzazione sierologica HLA classe I', 'Info Tipizzazione sierologica HLA classe I'),
       ('Tipizzazione sierologica HLA classe II', 'Info Tipizzazione sierologica HLA classe II'),
       ('Trombossano B2', 'Info Trombossano B2'),
       ('Viscosita ematica', 'Info Viscosita ematica'),
       ('Campylobacter antibiogramma', 'Info Campylobacter antibiogramma'),
       ('Campylobacter da coltura', 'Info Campylobacter da coltura'),
       ('Campylobacter esame colturale', 'Info Campylobacter esame colturale'),
       ('Chlamydie ricerca diretta (EIA)', 'Info Chlamydie ricerca diretta (EIA)'),
       ('Chlamydie ricerca diretta (IF)', 'Info Chlamydie ricerca diretta (IF)'),
       ('Chlamydie ricerca diretta (ibridazione)', 'Info Chlamydie ricerca diretta (ibridazione)'),
       ('Miceti anticorpi', 'Info Miceti anticorpi'),
       ('Miceti lieviti', 'Info Miceti lieviti'),
       ('Salmonelle da coltura', 'Info Salmonelle da coltura'),
       ('Shigelle', 'Info Shigelle'),
       ('Virus epatite B (HBV) Anticorpi Hbeag', 'Info Virus epatite B (HBV) Anticorpi Hbeag'),
       ('Analisi citogenetica per ricerca siti fragili', 'Info Analisi citogenetica per ricerca siti fragili'),
       ('Analisi citogenetica per scambi di cromatidi', 'Info Analisi citogenetica per scambi di cromatidi'),
       ('Analisi citogenetica per studio mosaicismo', 'Info Analisi citogenetica per studio mosaicismo'),
       ('Analisi citogenetica per studio riarrangiamenti',
        'Info Analisi citogenetica per studio riarrangiamenti'),
       ('Analisi DNA e ibridazione con sonda', 'Info Analisi DNA e ibridazione con sonda'),
       ('Analisi DNA per polimorfismo', 'Info Analisi DNA per polimorfismo'),
       ('Analisi mutazione del DNA con reazione polimerasica a catena',
        'Info Analisi mutazione del DNA con reazione polimerasica a catena'),
       ('Analisi di segmenti di DNA', 'Info Analisi di segmenti di DNA'),
       ('Cariotipo ad alta risoluzione', 'Info Cariotipo ad alta risoluzione'),
       ('Cariotipo da metafasi di fibroblasti', 'Info Cariotipo da metafasi di fibroblasti'),
       ('Cariotipo da metafasi linfocitarie', 'Info Cariotipo da metafasi linfocitarie'),
       ('Cariotipo da metafasi spontanee di villi corali',
        'Info Cariotipo da metafasi spontanee di villi corali'),
       ('Cariotipo da metafasi di midollo osseo', 'Info Cariotipo da metafasi di midollo osseo'),
       ('Colorazione aggiuntiva in bande: Actinomicina D',
        'Info Colorazione aggiuntiva in bande: Actinomicina D'),
       ('Colorazione aggiuntiva in bande: bandeggio C', 'Info Colorazione aggiuntiva in bande: bandeggio C'),
       ('Colorazione aggiuntiva in bande: bandeggio G', 'Info Colorazione aggiuntiva in bande: bandeggio G'),
       ('Colorazione aggiuntiva in bande: bandeggio G alta ris.',
        'Info Colorazione aggiuntiva in bande: bandeggio G alta ris.'),
       ('Colorazione aggiuntiva in bande: bandeggio NOR', 'Info Colorazione aggiuntiva in bande: bandeggio NOR'),
       ('Colorazione aggiuntiva in bande: bandeggio Q', 'Info Colorazione aggiuntiva in bande: bandeggio Q'),
       ('Colorazione aggiuntiva in bande: bandeggio R', 'Info Colorazione aggiuntiva in bande: bandeggio R'),
       ('Colorazione aggiuntiva in bande: bandeggio T', 'Info Colorazione aggiuntiva in bande: bandeggio T'),
       ('Colorazione aggiuntiva in bande: distamicina A', 'Info Colorazione aggiuntiva in bande: distamicina A'),
       ('Coltura di amniociti', 'Info Coltura di amniociti'),
       ('Coltura di linfociti periferici', 'Info Coltura di linfociti periferici'),
       ('Coltura di materiale abortivo', 'Info Coltura di materiale abortivo'),
       ('Coltura semisolida di cellule emopoietiche', 'Info Coltura semisolida di cellule emopoietiche'),
       ('Coltura di villi coriali a breve termine', 'Info Coltura di villi coriali a breve termine'),
       ('Coltura di cilli coriali', 'Info Coltura di cilli coriali'),
       ('Coltura per studio del cromosoma X', 'Info Coltura per studio del cromosoma X'),
       ('Conservazione campioni DNA RNA', 'Info Conservazione campioni DNA RNA'),
       ('Crioconservazione in azoto liquido di colture cellulari',
        'Info Crioconservazione in azoto liquido di colture cellulari'),
       ('Crioconservazione in azoto liquido di cellule e tessuti',
        'Info Crioconservazione in azoto liquido di cellule e tessuti'),
       ('Digestione DNA con enzimi', 'Info Digestione DNA con enzimi'),
       ('Estrazione DNA o RNA', 'Info Estrazione DNA o RNA'),
       ('Ibridazione con sonda molecolare', 'Info Ibridazione con sonda molecolare'),
       ('Ibridazione in SITU (Fish)', 'Info Ibridazione in SITU (Fish)'),
       ('Ricerca Mutazione (DGGE)', 'Info Ricerca Mutazione (DGGE)'),
       ('Ricerca mutazione (SSCP)', 'Info Ricerca mutazione (SSCP)'),
       ('Analisi DNA studio citometrico', 'Info Analisi DNA studio citometrico'),
       ('Orticarie fisiche', 'Info Orticarie fisiche'),
       ('Inalanti', 'Info Inalanti'),
       ('Test epicutanei a lettura ritardata', 'Info Test epicutanei a lettura ritardata'),
       ('Test a lettura immediata', 'Info Test a lettura immediata'),
       ('Tomoscintigrafia miocardica (PET)', 'Info Tomoscintigrafia miocardica (PET)'),
       ('Tomoscintigrafia Cerebrale (PET)', 'Info Tomoscintigrafia Cerebrale (PET)'),
       ('Radioterapia stereotassica', 'Info Radioterapia stereotassica'),
       ('Terapie e riabilitazioni', 'Info Terapie e riabilitazioni'),
       ('Esercizi respiratori per seduta collettiva', 'Info Esercizi respiratori per seduta collettiva'),
       ('Esercizi respiratori per seduta individuale', 'Info Esercizi respiratori per seduta individuale'),
       ('Tomoscintigrafia globale', 'Info Tomoscintigrafia globale'),
       ('Irradiazione cutanea', 'Info Irradiazione cutanea'),
       ('Terapia del dolore da metastasi ossee', 'Info Terapia del dolore da metastasi ossee'),
       ('Ablazione tartaro', 'Info Ablazione tartaro'),
       ('Sigillatura solchi e fossette', 'Info Sigillatura solchi e fossette'),
       ('Rimozione protesi dentarie', 'Info Rimozione protesi dentarie'),
       ('Immunizzazione allergia', 'Info Immunizzazione allergia'),
       ('Immunizzazione malattia autoimmune', 'Info Immunizzazione malattia autoimmune'),
       ('Terapia luce ultravioletta', 'Info Terapia luce ultravioletta'),
       ('Splintaggio per gruppi di 4 denti', 'Info Splintaggio per gruppi di 4 denti'),
       ('Trattamento applicazioni protesi semovibili', 'Info Trattamento applicazioni protesi semovibili');

INSERT INTO hs_exam(id)
SELECT id
FROM examination;

INSERT INTO examination(name, info)
VALUES ('Risonanza magnetica nucleare (RM) muscoloscheletrica',
        'Info Risonanza magnetica nucleare (RM) muscoloscheletrica'),
       ('Risonanza magnetica nucleare (RM) muscoloscheletrica senza e con contrasto',
        'Info Risonanza magnetica nucleare (RM) muscoloscheletrica senza e con contrasto'),
       ('Densitometria ossera', 'Info Densitometria ossera'),
       ('Deossicortisolo', 'Info Deossicortisolo'),
       ('Acido 5 idrossi 3 indolacetico', 'Info Acido 5 idrossi 3 indolacetico'),
       ('Acido delta', 'Info Acido delta'),
       ('Ala deidrasi', 'Info Ala deidrasi'),
       ('Alanina', 'Info Alanina'),
       ('Albumina', 'Info Albumina'),
       ('Aldolasi', 'Info Aldolasi'),
       ('Alfa amilasi', 'Info Alfa amilasi'),
       ('Alfa amilasi isoenzimi', 'Info Alfa amilasi isoenzimi'),
       ('Androstenediolo', 'Info Androstenediolo'),
       ('Aspartato aminotrasferiasi', 'Info Aspartato aminotrasferiasi'),
       ('Calcio totale', 'Info Calcio totale'),
       ('Colesterolo HDL', 'Info Colesterolo HDL'),
       ('Colesterolo LDL', 'Info Colesterolo LDL'),
       ('Colesterolo totale', 'Info Colesterolo totale'),
       ('Creatinchinasi', 'Info Creatinchinasi'),
       ('Creatinina', 'Info Creatinina'),
       ('Cromo', 'Info Cromo'),
       ('Enolasi', 'Info Enolasi'),
       ('Ferro', 'Info Ferro'),
       ('Fosfatasi acida', 'Info Fosfatasi acida'),
       ('Fosfatasi alcalina', 'Info Fosfatasi alcalina'),
       ('Fosfatasi alcalina isoenzima osseo', 'Info Fosfatasi alcalina isoenzima osseo'),
       ('Fosfato inorganico', 'Info Fosfato inorganico'),
       ('Lattato', 'Info Lattato'),
       ('Lipasi', 'Info Lipasi'),
       ('Magnesio', 'Info Magnesio'),
       ('Mioglobina', 'Info Mioglobina'),
       ('Potassio', 'Info Potassio'),
       ('Proteine', 'Info Proteine'),
       ('Sodio', 'Info Sodio'),
       ('Sudore', 'Info Sudore'),
       ('Trigliceridi', 'Info Trigliceridi'),
       ('Urato Urea', 'Info Urato Urea'),
       ('Alfa 2', 'Info Alfa 2'),
       ('Anticorpi anti microsomi', 'Info Anticorpi anti microsomi'),
       ('Antigene carboidratico 125', 'Info Antigene carboidratico 125'),
       ('Antigene carboidratico 15.3', 'Info Antigene carboidratico 15.3'),
       ('Antigene carboidratico 19.9', 'Info Antigene carboidratico 19.9'),
       ('Antigene carcino embrionario', 'Info Antigene carcino embrionario'),
       ('Antigeni HLA', 'Info Antigeni HLA'),
       ('Beta tromboglobulina', 'Info Beta tromboglobulina'),
       ('Cyfra', 'Info Cyfra'),
       ('Eparina', 'Info Eparina'),
       ('Fenotipo RH', 'Info Fenotipo RH'),
       ('Glicoproteina', 'Info Glicoproteina'),
       ('Gruppo sanguigno ABO e RH (D)', 'Info Gruppo sanguigno ABO e RH (D)'),
       ('Ige specifiche allergologiche', 'Info Ige specifiche allergologiche'),
       ('Ige specifiche allergologiche screening qualitativo',
        'Info Ige specifiche allergologiche screening qualitativo'),
       ('Inibitore attivatore del plasminogeno', 'Info Inibitore attivatore del plasminogeno'),
       ('Virus epatite B (HBV) Antigeni Hbeag', 'Info Virus epatite B (HBV) Antigeni Hbeag'),
       ('Analisi citogenetica per fragilita cromosomica', 'Info Analisi citogenetica per fragilita cromosomica'),
       ('Analisi mutazione del DNA con ibridazione sonde non radiomarcate',
        'Info Analisi mutazione del DNA con ibridazione sonde non radiomarcate'),
       ('Analisi mutazione del DNA con ibridazione sonde radiomarcate',
        'Info Analisi mutazione del DNA con ibridazione sonde radiomarcate'),
       ('Analisi mutazione del DNA con reverse dot blot', 'Info Analisi mutazione del DNA con reverse dot blot'),
       ('Analisi di polimorfismi', 'Info Analisi di polimorfismi');

INSERT INTO sp_exam(id)
SELECT examination.id
FROM examination LEFT JOIN hs_exam on examination.id = hs_exam.id
WHERE hs_exam.id IS NULL