INSERT INTO medicine(name, info)
VALUES ('Abacavir Sulfate', 'Info Abacavir Sulfate'),
       ('Abatacept', 'Info Abatacept'),
       ('Abilify', 'Info Abilify'),
       ('Acamprosate Calcium', 'Info Acamprosate Calcium'),
       ('Accretropin', 'Info Accretropin'),
       ('Aceon', 'Info Aceon'),
       ('Aci-Jel', 'Info Aci-Jel'),
       ('Acthrel', 'Info Acthrel'),
       ('Actimmune', 'Info Actimmune'),
       ('Actisite', 'Info Actisite'),
       ('Acular', 'Info Acular'),
       ('Acular LS', 'Info Acular LS'),
       ('Acuvail', 'Info Acuvail'),
       ('Adagen', 'Info Adagen'),
       ('Adapalene', 'Info Adapalene'),
       ('Adcirca', 'Info Adcirca'),
       ('Adefovir Dipivoxil', 'Info Adefovir Dipivoxil'),
       ('Adenoscan', 'Info Adenoscan'),
       ('Adenosine', 'Info Adenosine'),
       ('Adipex-P', 'Info Adipex-P'),
       ('AdreView', 'Info AdreView'),
       ('Advair HFA', 'Info Advair HFA'),
       ('Aerospan HFA', 'Info Aerospan HFA'),
       ('Agalsidase Beta', 'Info Agalsidase Beta'),
       ('Aggrenox', 'Info Aggrenox'),
       ('Akineton', 'Info Akineton'),
       ('Alamast', 'Info Alamast'),
       ('Albenza', 'Info Albenza'),
       ('Aldactazide', 'Info Aldactazide'),
       ('Aldactone', 'Info Aldactone'),
       ('Aldoril', 'Info Aldoril'),
       ('Aldurazyme', 'Info Aldurazyme'),
       ('Alemtuzumab', 'Info Alemtuzumab'),
       ('Alglucosidase Alfa', 'Info Alglucosidase Alfa'),
       ('Allegra-D', 'Info Allegra-D'),
       ('Allegra D 24 Hour', 'Info Allegra D 24 Hour'),
       ('Alli', 'Info Alli'),
       ('Aloprim', 'Info Aloprim'),
       ('Alora', 'Info Alora'),
       ('Alphanate', 'Info Alphanate'),
       ('Altace', 'Info Altace'),
       ('Altocor', 'Info Altocor'),
       ('Altoprev', 'Info Altoprev'),
       ('Alupent', 'Info Alupent'),
       ('Amantadine Hydrochloride', 'Info Amantadine Hydrochloride'),
       ('Amerge', 'Info Amerge'),
       ('Amifostine', 'Info Amifostine'),
       ('Amiloride', 'Info Amiloride'),
       ('Aminosalicylic Acid', 'Info Aminosalicylic Acid'),
       ('Aminosyn II 8.5%', 'Info Aminosyn II 8.5%'),
       ('Amlodipine Besylate', 'Info Amlodipine Besylate'),
       ('Amoxapine', 'Info Amoxapine'),
       ('Amytal Sodium', 'Info Amytal Sodium'),
       ('Anabolic steroids', 'Info Anabolic steroids'),
       ('Anadrol-50', 'Info Anadrol-50'),
       ('Antithrombin', 'Info Antithrombin'),
       ('Antivenin', 'Info Antivenin'),
       ('Antivert', 'Info Antivert'),
       ('Aredia', 'Info Aredia'),
       ('Aricept', 'Info Aricept'),
       ('Armodafinil', 'Info Armodafinil'),
       ('Arranon', 'Info Arranon'),
       ('Artane', 'Info Artane'),
       ('Asclera', 'Info Asclera'),
       ('Ascorbic Acid', 'Info Ascorbic Acid'),
       ('Astemizole', 'Info Astemizole'),
       ('Atacand', 'Info Atacand'),
       ('Atacand HCT', 'Info Atacand HCT'),
       ('Atazanavir Sulfate', 'Info Atazanavir Sulfate'),
       ('Atomoxetine HCl', 'Info Atomoxetine HCl'),
       ('Atridox', 'Info Atridox'),
       ('Atripla', 'Info Atripla'),
       ('Atropen', 'Info Atropen'),
       ('Augmentin XR', 'Info Augmentin XR'),
       ('Avage', 'Info Avage'),
       ('Avandia', 'Info Avandia'),
       ('Avastin', 'Info Avastin'),
       ('Avinza', 'Info Avinza'),
       ('Axid', 'Info Axid'),
       ('Azasan', 'Info Azasan'),
       ('Azasite', 'Info Azasite'),
       ('Azelaic Acid', 'Info Azelaic Acid'),
       ('Azelastine Hydrochloride', 'Info Azelastine Hydrochloride'),
       ('Azilect', 'Info Azilect'),
       ('Azmacort', 'Info Azmacort'),
       ('Balsalazide', 'Info Balsalazide'),
       ('Benazepril', 'Info Benazepril'),
       ('Benzocaine', 'Info Benzocaine'),
       ('Benzoyl Peroxide Gel', 'Info Benzoyl Peroxide Gel'),
       ('Benzphetamine', 'Info Benzphetamine'),
       ('Benztropine Mesylate', 'Info Benztropine Mesylate'),
       ('Bepreve', 'Info Bepreve'),
       ('Betagan', 'Info Betagan'),
       ('Bethanechol', 'Info Bethanechol'),
       ('Betimol', 'Info Betimol'),
       ('Betoptic S', 'Info Betoptic S'),
       ('Bevacizumab', 'Info Bevacizumab'),
       ('BiCNU', 'Info BiCNU'),
       ('Biperiden', 'Info Biperiden'),
       ('Bismuth Subcitrate Potassium', 'Info Bismuth Subcitrate Potassium'),
       ('Bismuth Subsalicylate', 'Info Bismuth Subsalicylate'),
       ('Blocadren', 'Info Blocadren'),
       ('Boniva', 'Info Boniva'),
       ('Bontril', 'Info Bontril'),
       ('Boostrix', 'Info Boostrix'),
       ('Botulinum Toxin Type A', 'Info Botulinum Toxin Type A'),
       ('Bravelle', 'Info Bravelle'),
       ('Brevibloc', 'Info Brevibloc'),
       ('Bromocriptine Mesylate', 'Info Bromocriptine Mesylate'),
       ('Brovana', 'Info Brovana'),
       ('Budesonide', 'Info Budesonide'),
       ('Buprenorphine', 'Info Buprenorphine'),
       ('Buspar', 'Info Buspar'),
       ('Buspirone', 'Info Buspirone'),
       ('Busulfan', 'Info Busulfan'),
       ('Busulfex', 'Info Busulfex'),
       ('Cabergoline', 'Info Cabergoline'),
       ('Caduet', 'Info Caduet'),
       ('Calcitonin-Salmon', 'Info Calcitonin-Salmon'),
       ('Calcium Chloride', 'Info Calcium Chloride'),
       ('Calcium Disodium Versenate', 'Info Calcium Disodium Versenate'),
       ('Calcium Gluconate', 'Info Calcium Gluconate'),
       ('Campral', 'Info Campral'),
       ('Canasa', 'Info Canasa'),
       ('Cancidas', 'Info Cancidas'),
       ('Captopril', 'Info Captopril'),
       ('Carac', 'Info Carac'),
       ('Carbatrol', 'Info Carbatrol'),
       ('Cardiolite', 'Info Cardiolite'),
       ('Carisoprodol', 'Info Carisoprodol'),
       ('Carmustine', 'Info Carmustine'),
       ('Carvedilol', 'Info Carvedilol'),
       ('Casodex', 'Info Casodex'),
       ('Caspofungin Acetate', 'Info Caspofungin Acetate'),
       ('Cataflam', 'Info Cataflam'),
       ('Catapres', 'Info Catapres'),
       ('Catapres-TTS', 'Info Catapres-TTS'),
       ('Caverject', 'Info Caverject'),
       ('Cedax', 'Info Cedax'),
       ('Cefditoren Pivoxil', 'Info Cefditoren Pivoxil'),
       ('Cefixime', 'Info Cefixime'),
       ('Cefizox', 'Info Cefizox'),
       ('Cefotetan', 'Info Cefotetan'),
       ('Ceftazidime', 'Info Ceftazidime'),
       ('Ceftibuten', 'Info Ceftibuten'),
       ('Ceftin', 'Info Ceftin'),
       ('Cefzil', 'Info Cefzil'),
       ('Celestone Soluspan', 'Info Celestone Soluspan'),
       ('Celexa', 'Info Celexa'),
       ('CellCept', 'Info CellCept'),
       ('Cellulose', 'Info Cellulose'),
       ('Celontin', 'Info Celontin'),
       ('Cephalexin', 'Info Cephalexin'),
       ('Cerebyx', 'Info Cerebyx'),
       ('Ceretec', 'Info Ceretec'),
       ('Cerubidine', 'Info Cerubidine'),
       ('Cerumenex', 'Info Cerumenex'),
       ('Cervidil', 'Info Cervidil'),
       ('Cetirizine', 'Info Cetirizine'),
       ('Cetraxal', 'Info Cetraxal'),
       ('Cetrotide', 'Info Cetrotide'),
       ('Cetuximab', 'Info Cetuximab'),
       ('Chantix', 'Info Chantix'),
       ('Chibroxin', 'Info Chibroxin'),
       ('Chlorambucil', 'Info Chlorambucil'),
       ('Chloramphenicol Sodium Succinate', 'Info Chloramphenicol Sodium Succinate'),
       ('Chloroprocaine', 'Info Chloroprocaine'),
       ('Chlorpheniramine Maleate', 'Info Chlorpheniramine Maleate'),
       ('Chlorpromazine', 'Info Chlorpromazine'),
       ('Chlorpropamide', 'Info Chlorpropamide'),
       ('Chlorthalidone', 'Info Chlorthalidone'),
       ('Cholera Vaccine', 'Info Cholera Vaccine'),
       ('Chorionic Gonadotropin', 'Info Chorionic Gonadotropin'),
       ('Ciclopirox Gel', 'Info Ciclopirox Gel'),
       ('Cilostazol', 'Info Cilostazol'),
       ('Cinobac', 'Info Cinobac'),
       ('Cipro', 'Info Cipro'),
       ('Cipro XR', 'Info Cipro XR'),
       ('Cisapride', 'Info Cisapride'),
       ('Clarinex', 'Info Clarinex'),
       ('Clarithromycin', 'Info Clarithromycin'),
       ('Claritin', 'Info Claritin'),
       ('Cleocin', 'Info Cleocin'),
       ('Cleviprex', 'Info Cleviprex'),
       ('Climara Pro', 'Info Climara Pro'),
       ('Clinoril', 'Info Clinoril'),
       ('Clobetasol Propionate', 'Info Clobetasol Propionate'),
       ('Clocortolone', 'Info Clocortolone'),
       ('Clofarabine', 'Info Clofarabine'),
       ('Clonidine', 'Info Clonidine'),
       ('Clorazepate Dipotassium', 'Info Clorazepate Dipotassium'),
       ('Clorpres', 'Info Clorpres'),
       ('Clotrimazole', 'Info Clotrimazole'),
       ('Cocaine', 'Info Cocaine'),
       ('Codeine', 'Info Codeine'),
       ('Cognex', 'Info Cognex'),
       ('Colazal', 'Info Colazal'),
       ('Colchicine', 'Info Colchicine'),
       ('Colcrys', 'Info Colcrys'),
       ('Colesevelam Hcl', 'Info Colesevelam Hcl'),
       ('Combivir', 'Info Combivir'),
       ('Conjugated Estrogens', 'Info Conjugated Estrogens'),
       ('Copaxone', 'Info Copaxone'),
       ('Corgard', 'Info Corgard'),
       ('Cosmegen', 'Info Cosmegen'),
       ('Coumadin', 'Info Coumadin'),
       ('Crolom', 'Info Crolom'),
       ('Cromolyn Sodium', 'Info Cromolyn Sodium'),
       ('Cubicin', 'Info Cubicin'),
       ('Curosurf', 'Info Curosurf'),
       ('Cuvposa', 'Info Cuvposa'),
       ('Cyanocobalamin', 'Info Cyanocobalamin'),
       ('Cyclobenzaprine Hcl', 'Info Cyclobenzaprine Hcl'),
       ('Cyclophosphamide', 'Info Cyclophosphamide'),
       ('Cyclosporine', 'Info Cyclosporine'),
       ('Cylert', 'Info Cylert'),
       ('Cymbalta', 'Info Cymbalta'),
       ('Cyproheptadine', 'Info Cyproheptadine'),
       ('Cystadane', 'Info Cystadane'),
       ('Cytogam', 'Info Cytogam'),
       ('Cytomel', 'Info Cytomel'),
       ('Dacarbazine', 'Info Dacarbazine'),
       ('Daraprim', 'Info Daraprim'),
       ('Darvocet-N', 'Info Darvocet-N'),
       ('Darvon Compound', 'Info Darvon Compound'),
       ('Dasatinib', 'Info Dasatinib'),
       ('Daunorubicin', 'Info Daunorubicin'),
       ('Daypro', 'Info Daypro'),
       ('Daypro Alta', 'Info Daypro Alta'),
       ('DDAVP Nasal Spray', 'Info DDAVP Nasal Spray'),
       ('Demadex', 'Info Demadex'),
       ('Demeclocycline HCl', 'Info Demeclocycline HCl'),
       ('Demser', 'Info Demser'),
       ('Depacon', 'Info Depacon'),
       ('DepoDur', 'Info DepoDur'),
       ('Desferal', 'Info Desferal'),
       ('Desogen', 'Info Desogen'),
       ('Desonate', 'Info Desonate'),
       ('DesOwen', 'Info DesOwen'),
       ('Detrol', 'Info Detrol'),
       ('Detrol LA', 'Info Detrol LA'),
       ('Dexlansoprazole', 'Info Dexlansoprazole'),
       ('Dexmethylphenidate Hydrochloride', 'Info Dexmethylphenidate Hydrochloride'),
       ('Dexrazoxane', 'Info Dexrazoxane'),
       ('Diamox Sequels', 'Info Diamox Sequels'),
       ('Dicyclomine', 'Info Dicyclomine'),
       ('Didanosine', 'Info Didanosine'),
       ('Diethylpropion', 'Info Diethylpropion'),
       ('Differin', 'Info Differin'),
       ('Diflucan', 'Info Diflucan'),
       ('Digoxin Immune Fab', 'Info Digoxin Immune Fab'),
       ('Diovan HCT', 'Info Diovan HCT'),
       ('Diphenhydramine', 'Info Diphenhydramine'),
       ('Diphtheria-Tetanus Vaccine', 'Info Diphtheria-Tetanus Vaccine'),
       ('Diprolene AF', 'Info Diprolene AF'),
       ('Dipyridamole', 'Info Dipyridamole'),
       ('Ditropan', 'Info Ditropan'),
       ('Dobutamine', 'Info Dobutamine'),
       ('Dofetilide', 'Info Dofetilide'),
       ('Dolophine', 'Info Dolophine'),
       ('Donepezil Hydrochloride', 'Info Donepezil Hydrochloride'),
       ('Dopamine Hydrochloride', 'Info Dopamine Hydrochloride'),
       ('Dopar', 'Info Dopar'),
       ('Dopram', 'Info Dopram'),
       ('Doral', 'Info Doral'),
       ('Doryx', 'Info Doryx'),
       ('Dorzolamide', 'Info Dorzolamide'),
       ('Dovonex', 'Info Dovonex'),
       ('Doxacurium Chloride', 'Info Doxacurium Chloride'),
       ('Doxapram', 'Info Doxapram'),
       ('Doxazosin Mesylate', 'Info Doxazosin Mesylate'),
       ('Doxepin', 'Info Doxepin'),
       ('Doxercalciferol', 'Info Doxercalciferol'),
       ('Doxil', 'Info Doxil'),
       ('Doxycycline', 'Info Doxycycline'),
       ('Doxycycline Hyclate', 'Info Doxycycline Hyclate'),
       ('Drisdol', 'Info Drisdol'),
       ('Dronabinol', 'Info Dronabinol'),
       ('Drospirenone and Estradiol', 'Info Drospirenone and Estradiol'),
       ('Duetact', 'Info Duetact'),
       ('Duraclon', 'Info Duraclon'),
       ('Dynacirc', 'Info Dynacirc'),
       ('Dynacirc CR', 'Info Dynacirc CR'),
       ('Dynapen', 'Info Dynapen'),
       ('Dyphylline', 'Info Dyphylline'),
       ('Econazole Nitrate', 'Info Econazole Nitrate'),
       ('Edrophonium', 'Info Edrophonium'),
       ('Efavirenz', 'Info Efavirenz'),
       ('Elaprase', 'Info Elaprase'),
       ('Elavil', 'Info Elavil'),
       ('Eletriptan hydrobromide', 'Info Eletriptan hydrobromide'),
       ('Eligard', 'Info Eligard'),
       ('Ellence', 'Info Ellence'),
       ('Elmiron', 'Info Elmiron'),
       ('Elspar', 'Info Elspar'),
       ('Emadine', 'Info Emadine'),
       ('Emcyt', 'Info Emcyt'),
       ('Emedastine', 'Info Emedastine'),
       ('Empirin', 'Info Empirin'),
       ('Emsam', 'Info Emsam'),
       ('Emtricitabine', 'Info Emtricitabine'),
       ('Emtriva', 'Info Emtriva'),
       ('Endocet', 'Info Endocet'),
       ('Endometrin', 'Info Endometrin'),
       ('Enflurane', 'Info Enflurane'),
       ('Engerix-B', 'Info Engerix-B'),
       ('Entereg', 'Info Entereg'),
       ('Eovist', 'Info Eovist'),
       ('Epinephrine', 'Info Epinephrine'),
       ('Epipen', 'Info Epipen'),
       ('Epirubicin hydrochloride', 'Info Epirubicin hydrochloride'),
       ('Epivir', 'Info Epivir'),
       ('Equetro', 'Info Equetro'),
       ('Eraxis', 'Info Eraxis'),
       ('Erbitux', 'Info Erbitux'),
       ('Ergocalciferol', 'Info Ergocalciferol'),
       ('Erlotinib', 'Info Erlotinib'),
       ('Erythrocin Stearate', 'Info Erythrocin Stearate'),
       ('Esomeprazole Sodium', 'Info Esomeprazole Sodium'),
       ('Essential Amino Acids', 'Info Essential Amino Acids'),
       ('Estrace', 'Info Estrace'),
       ('Estradiol', 'Info Estradiol'),
       ('Estradiol Acetate', 'Info Estradiol Acetate'),
       ('Estradiol valerate', 'Info Estradiol valerate'),
       ('Estratest', 'Info Estratest'),
       ('Estropipate', 'Info Estropipate'),
       ('Eszopiclone', 'Info Eszopiclone'),
       ('Etanercept', 'Info Etanercept'),
       ('Ethacrynic Acid', 'Info Ethacrynic Acid'),
       ('Ethambutol', 'Info Ethambutol'),
       ('Ethinyl Estradiol', 'Info Ethinyl Estradiol'),
       ('Ethiodol', 'Info Ethiodol'),
       ('Ethosuximide', 'Info Ethosuximide'),
       ('Etidocaine HCl', 'Info Etidocaine HCl'),
       ('Etidronate Disodium', 'Info Etidronate Disodium'),
       ('Etopophos', 'Info Etopophos'),
       ('Etrafon', 'Info Etrafon'),
       ('Eulexin', 'Info Eulexin'),
       ('Evista', 'Info Evista'),
       ('Evoxac', 'Info Evoxac'),
       ('Exelderm', 'Info Exelderm'),
       ('Exjade', 'Info Exjade'),
       ('Extavia', 'Info Extavia'),
       ('Factor IX Complex', 'Info Factor IX Complex'),
       ('Factrel', 'Info Factrel'),
       ('Famciclovir', 'Info Famciclovir'),
       ('Famotidine Injection', 'Info Famotidine Injection'),
       ('Famvir', 'Info Famvir'),
       ('Fansidar', 'Info Fansidar'),
       ('Febuxostat', 'Info Febuxostat'),
       ('Feridex I.V.', 'Info Feridex I.V.'),
       ('Fesoterodine Fumarate Extended', 'Info Fesoterodine Fumarate Extended'),
       ('Finacea', 'Info Finacea'),
       ('Flector', 'Info Flector'),
       ('Flonase', 'Info Flonase'),
       ('Florinef', 'Info Florinef'),
       ('Floxuridine', 'Info Floxuridine'),
       ('Fluconazole', 'Info Fluconazole'),
       ('Flucytosine', 'Info Flucytosine'),
       ('Fludara', 'Info Fludara'),
       ('Fludarabine Phosphate', 'Info Fludarabine Phosphate'),
       ('Fludrocortisone', 'Info Fludrocortisone'),
       ('Flumazenil', 'Info Flumazenil'),
       ('FluMist', 'Info FluMist'),
       ('Fluocinolone Acetonide', 'Info Fluocinolone Acetonide'),
       ('Fluoroplex', 'Info Fluoroplex'),
       ('Fluorouracil', 'Info Fluorouracil'),
       ('Fluoxetine Hydrochloride', 'Info Fluoxetine Hydrochloride'),
       ('Flurbiprofen', 'Info Flurbiprofen'),
       ('Fluress', 'Info Fluress'),
       ('Fluticasone Propionate', 'Info Fluticasone Propionate'),
       ('Fluvirin', 'Info Fluvirin'),
       ('FML', 'Info FML'),
       ('Folic Acid', 'Info Folic Acid'),
       ('Follitropin Alfa', 'Info Follitropin Alfa'),
       ('Follitropin Beta', 'Info Follitropin Beta'),
       ('Fomepizole', 'Info Fomepizole'),
       ('Foradil Aerolizer', 'Info Foradil Aerolizer'),
       ('Foradil Certihaler', 'Info Foradil Certihaler'),
       ('Forane', 'Info Forane'),
       ('Fosamax Plus D', 'Info Fosamax Plus D'),
       ('Fosamprenavir Calcium', 'Info Fosamprenavir Calcium'),
       ('Foscavir', 'Info Foscavir'),
       ('Fosphenytoin Sodium', 'Info Fosphenytoin Sodium'),
       ('Fragmin', 'Info Fragmin'),
       ('Frovatriptan Succinate', 'Info Frovatriptan Succinate'),
       ('Fulvestrant', 'Info Fulvestrant'),
       ('Fungizone', 'Info Fungizone'),
       ('Furadantin', 'Info Furadantin'),
       ('Furosemide', 'Info Furosemide'),
       ('Furoxone', 'Info Furoxone'),
       ('Fuzeon', 'Info Fuzeon'),
       ('Gabitril', 'Info Gabitril'),
       ('Gadobenate Dimeglumine', 'Info Gadobenate Dimeglumine'),
       ('Gadofosveset Trisodium', 'Info Gadofosveset Trisodium'),
       ('Galsulfase', 'Info Galsulfase'),
       ('Gamunex', 'Info Gamunex'),
       ('Geocillin', 'Info Geocillin'),
       ('Geodon', 'Info Geodon'),
       ('Gleevec', 'Info Gleevec'),
       ('Glucophage XR', 'Info Glucophage XR'),
       ('Glucovance', 'Info Glucovance'),
       ('Glyburide', 'Info Glyburide'),
       ('Glycopyrrolate', 'Info Glycopyrrolate'),
       ('Glynase', 'Info Glynase'),
       ('Glyset', 'Info Glyset'),
       ('Gold Sodium Thiomalate', 'Info Gold Sodium Thiomalate'),
       ('Gonadorelin', 'Info Gonadorelin'),
       ('Gonal-F', 'Info Gonal-F'),
       ('Gonal-f RFF', 'Info Gonal-f RFF'),
       ('Grifulvin V', 'Info Grifulvin V'),
       ('Griseofulvin', 'Info Griseofulvin'),
       ('Guanethidine Monosulfate', 'Info Guanethidine Monosulfate'),
       ('Gynazole', 'Info Gynazole'),
       ('Haemophilus b Conjugate Vaccine', 'Info Haemophilus b Conjugate Vaccine'),
       ('Halcinonide', 'Info Halcinonide'),
       ('Haldol', 'Info Haldol'),
       ('Halobetasol Propionate', 'Info Halobetasol Propionate'),
       ('Haloperidol', 'Info Haloperidol'),
       ('Healon', 'Info Healon'),
       ('HepaGam B', 'Info HepaGam B'),
       ('Heparin Lock Flush', 'Info Heparin Lock Flush'),
       ('HepatAmine', 'Info HepatAmine'),
       ('Hepatitis A Vaccine, Inactivated', 'Info Hepatitis A Vaccine, Inactivated'),
       ('Hepatitis B Immune Globulin', 'Info Hepatitis B Immune Globulin'),
       ('Hepflush-10', 'Info Hepflush-10'),
       ('Herceptin', 'Info Herceptin'),
       ('Hexachlorophene', 'Info Hexachlorophene'),
       ('HibTITER', 'Info HibTITER'),
       ('Hivid', 'Info Hivid'),
       ('Human Secretin', 'Info Human Secretin'),
       ('Humira', 'Info Humira'),
       ('Humulin N', 'Info Humulin N'),
       ('Hyalgan', 'Info Hyalgan'),
       ('Hydrocodone Bitartrate and Acetaminophen', 'Info Hydrocodone Bitartrate and Acetaminophen'),
       ('Hydroxyethyl Starch', 'Info Hydroxyethyl Starch'),
       ('Hylenex', 'Info Hylenex'),
       ('Hyoscyamine', 'Info Hyoscyamine'),
       ('Hytrin', 'Info Hytrin'),
       ('Ibuprofen Lysine', 'Info Ibuprofen Lysine'),
       ('Idamycin', 'Info Idamycin'),
       ('Idamycin PFS', 'Info Idamycin PFS'),
       ('Ifosfamide', 'Info Ifosfamide'),
       ('Iloperidone', 'Info Iloperidone'),
       ('Imipramine', 'Info Imipramine'),
       ('Imiquimod', 'Info Imiquimod'),
       ('Imitrex', 'Info Imitrex'),
       ('Immune Globulin', 'Info Immune Globulin'),
       ('Immune Globulin Intravenous', 'Info Immune Globulin Intravenous'),
       ('Implanon', 'Info Implanon'),
       ('Inderal LA', 'Info Inderal LA'),
       ('Indigo Carmine', 'Info Indigo Carmine'),
       ('InnoPran XL', 'Info InnoPran XL'),
       ('Insulin', 'Info Insulin'),
       ('Insulin Aspart', 'Info Insulin Aspart'),
       ('Intelence', 'Info Intelence'),
       ('Intralipid 20%', 'Info Intralipid 20%'),
       ('Intuniv', 'Info Intuniv'),
       ('Invanz', 'Info Invanz'),
       ('Invega', 'Info Invega'),
       ('Inversine', 'Info Inversine'),
       ('Ionamin', 'Info Ionamin'),
       ('Irinotecan Hydrochloride', 'Info Irinotecan Hydrochloride'),
       ('Isentress', 'Info Isentress'),
       ('Ismo', 'Info Ismo'),
       ('Isocarboxazid', 'Info Isocarboxazid'),
       ('Isoptin SR', 'Info Isoptin SR'),
       ('Isopto Carpine', 'Info Isopto Carpine'),
       ('Isopto Hyoscine', 'Info Isopto Hyoscine'),
       ('Istalol', 'Info Istalol'),
       ('Isuprel', 'Info Isuprel'),
       ('Ixempra', 'Info Ixempra'),
       ('Jalyn', 'Info Jalyn'),
       ('Janumet', 'Info Janumet'),
       ('Je-Vax', 'Info Je-Vax'),
       ('K-LOR', 'Info K-LOR'),
       ('Kaletra', 'Info Kaletra'),
       ('Kariva', 'Info Kariva'),
       ('Kenalog', 'Info Kenalog'),
       ('Kinlytic', 'Info Kinlytic'),
       ('Klonopin', 'Info Klonopin'),
       ('Kuvan', 'Info Kuvan'),
       ('Kytril', 'Info Kytril'),
       ('Labetalol', 'Info Labetalol'),
       ('lacosamide', 'Info lacosamide'),
       ('Lamisil', 'Info Lamisil'),
       ('Lamivudine / Zidovudine', 'Info Lamivudine / Zidovudine'),
       ('Latanoprost', 'Info Latanoprost'),
       ('Letairis', 'Info Letairis'),
       ('Letrozole', 'Info Letrozole'),
       ('Leuprolide Acetate', 'Info Leuprolide Acetate'),
       ('Leustatin', 'Info Leustatin'),
       ('Levalbuterol', 'Info Levalbuterol'),
       ('Levaquin', 'Info Levaquin'),
       ('Levemir', 'Info Levemir'),
       ('Levo-T', 'Info Levo-T'),
       ('Levocabastine', 'Info Levocabastine'),
       ('Levofloxacin', 'Info Levofloxacin'),
       ('Levonorgestrel', 'Info Levonorgestrel'),
       ('Levonorgestrel and Ethinyl Estradiol', 'Info Levonorgestrel and Ethinyl Estradiol'),
       ('Levonorgestrel Implants', 'Info Levonorgestrel Implants'),
       ('Levonorgestrel, Ethinyl Estradiol', 'Info Levonorgestrel, Ethinyl Estradiol'),
       ('Lexapro', 'Info Lexapro'),
       ('Lexiscan', 'Info Lexiscan'),
       ('Lexxel', 'Info Lexxel'),
       ('Librium', 'Info Librium'),
       ('Lidex', 'Info Lidex'),
       ('Lidoderm', 'Info Lidoderm'),
       ('Linezolid', 'Info Linezolid'),
       ('Lipofen', 'Info Lipofen'),
       ('Liposyn II', 'Info Liposyn II'),
       ('Liraglutide', 'Info Liraglutide'),
       ('Lisinopril and Hydrochlorothiazide', 'Info Lisinopril and Hydrochlorothiazide'),
       ('Locoid', 'Info Locoid'),
       ('Lodine', 'Info Lodine'),
       ('Loperamide Hcl', 'Info Loperamide Hcl'),
       ('Lopid', 'Info Lopid'),
       ('Loprox Gel', 'Info Loprox Gel'),
       ('Loracarbef', 'Info Loracarbef'),
       ('Lortab', 'Info Lortab'),
       ('Lotemax', 'Info Lotemax'),
       ('Lotensin', 'Info Lotensin'),
       ('Lotronex', 'Info Lotronex'),
       ('Lovenox', 'Info Lovenox'),
       ('Loxapine', 'Info Loxapine'),
       ('Loxitane', 'Info Loxitane'),
       ('Lucentis', 'Info Lucentis'),
       ('Luvox CR', 'Info Luvox CR'),
       ('Lybrel', 'Info Lybrel'),
       ('M-M-R', 'Info M-M-R'),
       ('Malarone', 'Info Malarone'),
       ('Malathion', 'Info Malathion'),
       ('Mandol', 'Info Mandol'),
       ('Mangafodipir', 'Info Mangafodipir'),
       ('Maraviroc', 'Info Maraviroc'),
       ('Marinol', 'Info Marinol'),
       ('Maxitrol', 'Info Maxitrol'),
       ('Mecasermin', 'Info Mecasermin'),
       ('Meclofenamate', 'Info Meclofenamate'),
       ('Mefloquine', 'Info Mefloquine'),
       ('Melphalan', 'Info Melphalan'),
       ('Menactra', 'Info Menactra'),
       ('Menest', 'Info Menest'),
       ('Menotropins', 'Info Menotropins'),
       ('Mephobarbital', 'Info Mephobarbital'),
       ('Mequinol and Tretinoin', 'Info Mequinol and Tretinoin'),
       ('Meropenem', 'Info Meropenem'),
       ('Merrem I.V.', 'Info Merrem I.V.'),
       ('Mesalamine', 'Info Mesalamine'),
       ('Mesna', 'Info Mesna'),
       ('Mestinon', 'Info Mestinon'),
       ('Metadate ER', 'Info Metadate ER'),
       ('Metaglip', 'Info Metaglip'),
       ('Metaproterenol Sulfate', 'Info Metaproterenol Sulfate'),
       ('Metaxalone', 'Info Metaxalone'),
       ('Metformin Hcl', 'Info Metformin Hcl'),
       ('Methadone Hydrochloride', 'Info Methadone Hydrochloride'),
       ('Methadose Oral Concentrate', 'Info Methadose Oral Concentrate'),
       ('Methazolamide', 'Info Methazolamide'),
       ('Methenamine Hippurate', 'Info Methenamine Hippurate'),
       ('Methergine', 'Info Methergine'),
       ('Methohexital Sodium', 'Info Methohexital Sodium'),
       ('Methyclothiazide', 'Info Methyclothiazide'),
       ('Methyldopa', 'Info Methyldopa'),
       ('Methylene Blue', 'Info Methylene Blue'),
       ('Methylergonovine Maleate', 'Info Methylergonovine Maleate'),
       ('Methylin', 'Info Methylin'),
       ('Methyltestosterone', 'Info Methyltestosterone'),
       ('Metipranolol', 'Info Metipranolol'),
       ('Metoclopramide', 'Info Metoclopramide'),
       ('Metoprolol Tartrate', 'Info Metoprolol Tartrate'),
       ('MetroLotion', 'Info MetroLotion'),
       ('Metyrapone', 'Info Metyrapone'),
       ('Metyrosine', 'Info Metyrosine'),
       ('Miacalcin', 'Info Miacalcin'),
       ('Micro-K', 'Info Micro-K'),
       ('Micronase', 'Info Micronase'),
       ('Micronized Glyburide', 'Info Micronized Glyburide'),
       ('Midazolam', 'Info Midazolam'),
       ('Midodrine Hydrochloride', 'Info Midodrine Hydrochloride'),
       ('Milrinone', 'Info Milrinone'),
       ('Minocin', 'Info Minocin'),
       ('Minocycline', 'Info Minocycline'),
       ('Minoxidil', 'Info Minoxidil'),
       ('Miochol-E', 'Info Miochol-E'),
       ('Miostat', 'Info Miostat'),
       ('Mitomycin', 'Info Mitomycin'),
       ('Mobic', 'Info Mobic'),
       ('Modafinil', 'Info Modafinil'),
       ('Monistat', 'Info Monistat'),
       ('Monistat-Derm', 'Info Monistat-Derm'),
       ('Morrhuate Sodium', 'Info Morrhuate Sodium'),
       ('Motrin', 'Info Motrin'),
       ('Moxatag', 'Info Moxatag'),
       ('Mozobil', 'Info Mozobil'),
       ('Multaq', 'Info Multaq'),
       ('Multi Vitamin', 'Info Multi Vitamin'),
       ('Multihance', 'Info Multihance'),
       ('Mustargen', 'Info Mustargen'),
       ('Mutamycin', 'Info Mutamycin'),
       ('Myambutol', 'Info Myambutol'),
       ('Mycamine', 'Info Mycamine'),
       ('Mycelex', 'Info Mycelex'),
       ('Mycophenolic Acid', 'Info Mycophenolic Acid'),
       ('Myfortic', 'Info Myfortic'),
       ('Mykrox', 'Info Mykrox'),
       ('Myobloc', 'Info Myobloc'),
       ('Myochrysine', 'Info Myochrysine'),
       ('Nafcillin Sodium', 'Info Nafcillin Sodium'),
       ('Naftifine Hcl', 'Info Naftifine Hcl'),
       ('Nalmefene Hydrochloride', 'Info Nalmefene Hydrochloride'),
       ('Naltrexone', 'Info Naltrexone'),
       ('Naproxen', 'Info Naproxen'),
       ('Nascobal', 'Info Nascobal'),
       ('Natazia', 'Info Natazia'),
       ('Natrecor', 'Info Natrecor'),
       ('Navelbine', 'Info Navelbine'),
       ('Nebcin', 'Info Nebcin'),
       ('Nebivolol Tablets', 'Info Nebivolol Tablets'),
       ('Nedocromil', 'Info Nedocromil'),
       ('Nelarabine', 'Info Nelarabine'),
       ('Nelfinavir Mesylate', 'Info Nelfinavir Mesylate'),
       ('NeoProfen', 'Info NeoProfen'),
       ('Neostigmine', 'Info Neostigmine'),
       ('Nephramine', 'Info Nephramine'),
       ('Nesacaine', 'Info Nesacaine'),
       ('Neulasta', 'Info Neulasta'),
       ('Nexavar', 'Info Nexavar'),
       ('Niaspan', 'Info Niaspan'),
       ('Nicotrol', 'Info Nicotrol'),
       ('Nicotrol NS', 'Info Nicotrol NS'),
       ('Nilandron', 'Info Nilandron'),
       ('Nilotinib Capsules', 'Info Nilotinib Capsules'),
       ('Nimbex', 'Info Nimbex'),
       ('Nimotop', 'Info Nimotop'),
       ('Nitroglycerin', 'Info Nitroglycerin'),
       ('NitroMist', 'Info NitroMist'),
       ('Nizatidine', 'Info Nizatidine'),
       ('Nizoral', 'Info Nizoral'),
       ('Noctec', 'Info Noctec'),
       ('Nor-QD', 'Info Nor-QD'),
       ('Norethindrone and Ethinyl Estradiol', 'Info Norethindrone and Ethinyl Estradiol'),
       ('Noritate', 'Info Noritate'),
       ('Nortriptyline Hydrochloride', 'Info Nortriptyline Hydrochloride'),
       ('Norvasc', 'Info Norvasc'),
       ('NovoLog Mix 70/30', 'Info NovoLog Mix 70/30'),
       ('Novoseven', 'Info Novoseven'),
       ('Numorphan', 'Info Numorphan'),
       ('Nutropin AQ', 'Info Nutropin AQ'),
       ('Nutropin Depot', 'Info Nutropin Depot'),
       ('Nydrazid', 'Info Nydrazid'),
       ('Omeprazole', 'Info Omeprazole'),
       ('Omnaris', 'Info Omnaris'),
       ('Opana', 'Info Opana'),
       ('Opticrom', 'Info Opticrom'),
       ('OptiMARK', 'Info OptiMARK'),
       ('Optipranolol', 'Info Optipranolol'),
       ('Oracea', 'Info Oracea'),
       ('Oraqix', 'Info Oraqix'),
       ('Orfadin', 'Info Orfadin'),
       ('Orlaam', 'Info Orlaam'),
       ('Orlistat', 'Info Orlistat'),
       ('Orudis', 'Info Orudis'),
       ('Ovcon', 'Info Ovcon'),
       ('Ovide', 'Info Ovide'),
       ('Oxandrolone', 'Info Oxandrolone'),
       ('Oxaprozin', 'Info Oxaprozin'),
       ('Oxistat', 'Info Oxistat'),
       ('Oxsoralen-Ultra', 'Info Oxsoralen-Ultra'),
       ('Oxycodone HCl', 'Info Oxycodone HCl'),
       ('Oxycodone Hydrochloride', 'Info Oxycodone Hydrochloride'),
       ('Oxycontin', 'Info Oxycontin'),
       ('Oxymetholone', 'Info Oxymetholone'),
       ('Oxymorphone', 'Info Oxymorphone'),
       ('Oxytetracycline', 'Info Oxytetracycline'),
       ('Paclitaxel', 'Info Paclitaxel'),
       ('Palifermin', 'Info Palifermin'),
       ('Paliperidone', 'Info Paliperidone'),
       ('Palonosetron hydrochloride', 'Info Palonosetron hydrochloride'),
       ('Panhematin', 'Info Panhematin'),
       ('Pantoprazole', 'Info Pantoprazole'),
       ('Parafon Forte', 'Info Parafon Forte'),
       ('Parnate', 'Info Parnate'),
       ('Paser', 'Info Paser'),
       ('Pataday', 'Info Pataday'),
       ('Pazopanib', 'Info Pazopanib'),
       ('Pediapred', 'Info Pediapred'),
       ('PEG 3350', 'Info PEG 3350'),
       ('Pegfilgrastim', 'Info Pegfilgrastim'),
       ('Pemirolast Potassium', 'Info Pemirolast Potassium'),
       ('Penciclovir', 'Info Penciclovir'),
       ('Penicillamine', 'Info Penicillamine'),
       ('Penlac', 'Info Penlac'),
       ('Pentetate Zinc Trisodium', 'Info Pentetate Zinc Trisodium'),
       ('Pentobarbital', 'Info Pentobarbital'),
       ('Pentoxifylline', 'Info Pentoxifylline'),
       ('Perflutren', 'Info Perflutren'),
       ('Perindopril Erbumine', 'Info Perindopril Erbumine'),
       ('Permax', 'Info Permax'),
       ('Persantine', 'Info Persantine'),
       ('Pfizerpen', 'Info Pfizerpen'),
       ('Phenazopyridine', 'Info Phenazopyridine'),
       ('Phenelzine', 'Info Phenelzine'),
       ('Phenobarbital', 'Info Phenobarbital'),
       ('Phenoxybenzamine', 'Info Phenoxybenzamine'),
       ('Phenylephrine HCl', 'Info Phenylephrine HCl'),
       ('Phenylephrine Hydrochloride', 'Info Phenylephrine Hydrochloride'),
       ('Phenytoin', 'Info Phenytoin'),
       ('Phosphate', 'Info Phosphate'),
       ('Photofrin', 'Info Photofrin'),
       ('Pilocarpine Hydrochloride', 'Info Pilocarpine Hydrochloride'),
       ('Pilopine HS', 'Info Pilopine HS'),
       ('Pindolol', 'Info Pindolol'),
       ('Pipracil', 'Info Pipracil'),
       ('Piroxicam', 'Info Piroxicam'),
       ('Plaquenil', 'Info Plaquenil'),
       ('PlasmaLyte A', 'Info PlasmaLyte A'),
       ('Plavix', 'Info Plavix'),
       ('Plenaxis', 'Info Plenaxis'),
       ('Pletal', 'Info Pletal'),
       ('Pneumovax', 'Info Pneumovax'),
       ('Podophyllin', 'Info Podophyllin'),
       ('Polidocanol', 'Info Polidocanol'),
       ('Polyethylene Glycol 3350', 'Info Polyethylene Glycol 3350'),
       ('Polythiazide', 'Info Polythiazide'),
       ('Pramipexole', 'Info Pramipexole'),
       ('Pred-G', 'Info Pred-G'),
       ('Prednicarbate', 'Info Prednicarbate'),
       ('Prednisolone Acetate', 'Info Prednisolone Acetate'),
       ('Prednisone', 'Info Prednisone'),
       ('Prefest', 'Info Prefest'),
       ('Pregnyl', 'Info Pregnyl'),
       ('Premarin', 'Info Premarin'),
       ('Prepidil', 'Info Prepidil'),
       ('Prevpac', 'Info Prevpac'),
       ('Priftin', 'Info Priftin'),
       ('Primacor', 'Info Primacor'),
       ('Primaquine', 'Info Primaquine'),
       ('Primidone', 'Info Primidone'),
       ('Prinivil', 'Info Prinivil'),
       ('Prinzide', 'Info Prinzide'),
       ('Pristiq', 'Info Pristiq'),
       ('Procainamide', 'Info Procainamide'),
       ('Procalamine', 'Info Procalamine'),
       ('Prochlorperazine Maleate', 'Info Prochlorperazine Maleate'),
       ('ProHance', 'Info ProHance'),
       ('Proleukin', 'Info Proleukin'),
       ('Prolixin', 'Info Prolixin'),
       ('Promethazine HCl', 'Info Promethazine HCl'),
       ('Promethazine Hydrochloride', 'Info Promethazine Hydrochloride'),
       ('Prometrium', 'Info Prometrium'),
       ('Propecia', 'Info Propecia'),
       ('Proquin XR', 'Info Proquin XR'),
       ('Prostin VR Pediatric', 'Info Prostin VR Pediatric'),
       ('Protein C Concentrate', 'Info Protein C Concentrate'),
       ('Protopic', 'Info Protopic'),
       ('Protriptyline Hydrochloride', 'Info Protriptyline Hydrochloride'),
       ('Proventil HFA', 'Info Proventil HFA'),
       ('Provisc', 'Info Provisc'),
       ('Provocholine', 'Info Provocholine'),
       ('Pulmicort Flexhaler', 'Info Pulmicort Flexhaler'),
       ('Pylera', 'Info Pylera'),
       ('Pyrazinamide', 'Info Pyrazinamide'),
       ('Pyridium', 'Info Pyridium'),
       ('Pyridostigmine', 'Info Pyridostigmine'),
       ('Qualaquin', 'Info Qualaquin'),
       ('Quazepam', 'Info Quazepam'),
       ('Quinidine Sulfate', 'Info Quinidine Sulfate'),
       ('Quixin', 'Info Quixin'),
       ('Rabies Vaccine', 'Info Rabies Vaccine'),
       ('Raltegravir', 'Info Raltegravir'),
       ('Ranexa', 'Info Ranexa'),
       ('Ranitidine Hcl', 'Info Ranitidine Hcl'),
       ('Rapamune', 'Info Rapamune'),
       ('Rasagiline', 'Info Rasagiline'),
       ('Raxar', 'Info Raxar'),
       ('Rebetol', 'Info Rebetol'),
       ('Remicade', 'Info Remicade'),
       ('Remifentanil', 'Info Remifentanil'),
       ('Renese', 'Info Renese'),
       ('ReoPro', 'Info ReoPro'),
       ('Rescriptor', 'Info Rescriptor'),
       ('Rescula', 'Info Rescula'),
       ('Revatio', 'Info Revatio'),
       ('Revex', 'Info Revex'),
       ('Revia', 'Info Revia'),
       ('Reyataz', 'Info Reyataz'),
       ('Rezulin', 'Info Rezulin'),
       ('Rhinocort Aqua', 'Info Rhinocort Aqua'),
       ('Rhogam Ultra-Filtered Plus', 'Info Rhogam Ultra-Filtered Plus'),
       ('RiaSTAP', 'Info RiaSTAP'),
       ('Rifamate', 'Info Rifamate'),
       ('Riomet', 'Info Riomet'),
       ('Risperidone', 'Info Risperidone'),
       ('Ritalin', 'Info Ritalin'),
       ('Rituximab', 'Info Rituximab'),
       ('Rivastigmine Tartrate', 'Info Rivastigmine Tartrate'),
       ('Robinul', 'Info Robinul'),
       ('Rosiglitazone Maleate', 'Info Rosiglitazone Maleate'),
       ('Rotarix', 'Info Rotarix'),
       ('RotaTeq', 'Info RotaTeq'),
       ('Roxicet', 'Info Roxicet'),
       ('Roxicodone', 'Info Roxicodone'),
       ('Ryzolt', 'Info Ryzolt'),
       ('Sabril', 'Info Sabril'),
       ('Sacrosidase', 'Info Sacrosidase'),
       ('Samsca', 'Info Samsca'),
       ('Sanctura', 'Info Sanctura'),
       ('Santyl', 'Info Santyl'),
       ('Saphris', 'Info Saphris'),
       ('Scopolamine', 'Info Scopolamine'),
       ('Seasonale', 'Info Seasonale'),
       ('Selegiline Hydrochloride', 'Info Selegiline Hydrochloride'),
       ('Selsun', 'Info Selsun'),
       ('Septra', 'Info Septra'),
       ('Serax', 'Info Serax'),
       ('Sertraline Hcl', 'Info Sertraline Hcl'),
       ('Serzone', 'Info Serzone'),
       ('Sevoflurane', 'Info Sevoflurane'),
       ('Sibutramine Hydrochloride Monohydrate', 'Info Sibutramine Hydrochloride Monohydrate'),
       ('Silenor', 'Info Silenor'),
       ('Simponi', 'Info Simponi'),
       ('Sirolimus', 'Info Sirolimus'),
       ('Sitagliptin Metformin HCL', 'Info Sitagliptin Metformin HCL'),
       ('Slow-K', 'Info Slow-K'),
       ('Sodium Bicarbonate', 'Info Sodium Bicarbonate'),
       ('Sodium ferric gluconate', 'Info Sodium ferric gluconate'),
       ('Sodium Iodide I 131', 'Info Sodium Iodide I 131'),
       ('Sodium Polystyrene Sulfonate', 'Info Sodium Polystyrene Sulfonate'),
       ('Sodium Sulfacetamide', 'Info Sodium Sulfacetamide'),
       ('Soma Compound', 'Info Soma Compound'),
       ('Somatrem', 'Info Somatrem'),
       ('Somatropin', 'Info Somatropin'),
       ('Sonata', 'Info Sonata'),
       ('Soriatane', 'Info Soriatane'),
       ('Sotradecol', 'Info Sotradecol'),
       ('Spiriva', 'Info Spiriva'),
       ('Sporanox', 'Info Sporanox'),
       ('Sprix', 'Info Sprix'),
       ('Sprycel', 'Info Sprycel'),
       ('Stalevo', 'Info Stalevo'),
       ('Starlix', 'Info Starlix'),
       ('Stavudine', 'Info Stavudine'),
       ('Streptokinase', 'Info Streptokinase'),
       ('Strontium-89', 'Info Strontium-89'),
       ('Suboxone', 'Info Suboxone'),
       ('Succimer', 'Info Succimer'),
       ('Succinylcholine Chloride', 'Info Succinylcholine Chloride'),
       ('Sucralfate', 'Info Sucralfate'),
       ('Sulfamylon', 'Info Sulfamylon'),
       ('Sunitinib Malate', 'Info Sunitinib Malate'),
       ('Sutent', 'Info Sutent'),
       ('Synthroid', 'Info Synthroid'),
       ('Synvisc', 'Info Synvisc'),
       ('Syprine', 'Info Syprine'),
       ('Tacrolimus', 'Info Tacrolimus'),
       ('Talacen', 'Info Talacen'),
       ('Talwin Nx', 'Info Talwin Nx'),
       ('Tamiflu', 'Info Tamiflu'),
       ('Tamoxifen Citrate', 'Info Tamoxifen Citrate'),
       ('Tapazole', 'Info Tapazole'),
       ('Targretin', 'Info Targretin'),
       ('Tasmar', 'Info Tasmar'),
       ('Tegretol', 'Info Tegretol'),
       ('Tekturna HCT', 'Info Tekturna HCT'),
       ('Telavancin', 'Info Telavancin'),
       ('Telbivudine', 'Info Telbivudine'),
       ('Telmisartan', 'Info Telmisartan'),
       ('Temovate Scalp', 'Info Temovate Scalp'),
       ('Temozolomide', 'Info Temozolomide'),
       ('Temsirolimus', 'Info Temsirolimus'),
       ('Teniposide', 'Info Teniposide'),
       ('Terazol 3, Terazol 7', 'Info Terazol 3, Terazol 7'),
       ('Tessalon', 'Info Tessalon'),
       ('Testolactone', 'Info Testolactone'),
       ('Testred', 'Info Testred'),
       ('Teveten HCT', 'Info Teveten HCT'),
       ('Theracys', 'Info Theracys'),
       ('Thiabendazole', 'Info Thiabendazole'),
       ('Thiethylperazine', 'Info Thiethylperazine'),
       ('Thiopental Sodium', 'Info Thiopental Sodium'),
       ('Thioridazine', 'Info Thioridazine'),
       ('Thiothixene Hcl', 'Info Thiothixene Hcl'),
       ('Thrombin', 'Info Thrombin'),
       ('Thyrolar', 'Info Thyrolar'),
       ('Thyrotropin Alfa', 'Info Thyrotropin Alfa'),
       ('Tiazac', 'Info Tiazac'),
       ('Ticarcillin', 'Info Ticarcillin'),
       ('Tinzaparin', 'Info Tinzaparin'),
       ('Tirosint', 'Info Tirosint'),
       ('Tizanidine', 'Info Tizanidine'),
       ('Tobrex', 'Info Tobrex'),
       ('Tofranil-PM', 'Info Tofranil-PM'),
       ('Tolazamide', 'Info Tolazamide'),
       ('Tolmetin Sodium', 'Info Tolmetin Sodium'),
       ('Tonocard', 'Info Tonocard'),
       ('Topicort', 'Info Topicort'),
       ('Topiramate', 'Info Topiramate'),
       ('Topotecan Hydrochloride', 'Info Topotecan Hydrochloride'),
       ('Toradol', 'Info Toradol'),
       ('Torsemide', 'Info Torsemide'),
       ('Toviaz', 'Info Toviaz'),
       ('Tramadol Hcl', 'Info Tramadol Hcl'),
       ('Tranxene', 'Info Tranxene'),
       ('Trastuzumab', 'Info Trastuzumab'),
       ('Trasylol', 'Info Trasylol'),
       ('Tretinoin', 'Info Tretinoin'),
       ('Trexall', 'Info Trexall'),
       ('Tri-Sprintec', 'Info Tri-Sprintec'),
       ('Triamcinolone Acetonide', 'Info Triamcinolone Acetonide'),
       ('Triazolam', 'Info Triazolam'),
       ('Tribenzor', 'Info Tribenzor'),
       ('Trientine', 'Info Trientine'),
       ('Trihexyphenidyl', 'Info Trihexyphenidyl'),
       ('Trilipix', 'Info Trilipix'),
       ('Trilisate', 'Info Trilisate'),
       ('Trimethadione', 'Info Trimethadione'),
       ('Trimethoprim', 'Info Trimethoprim'),
       ('Trimethoprim and Sulfamethoxazole', 'Info Trimethoprim and Sulfamethoxazole'),
       ('Trimetrexate Glucuronate', 'Info Trimetrexate Glucuronate'),
       ('Trizivir', 'Info Trizivir'),
       ('Trovafloxacin', 'Info Trovafloxacin'),
       ('Trovan', 'Info Trovan'),
       ('Trusopt', 'Info Trusopt'),
       ('Trypan Blue', 'Info Trypan Blue'),
       ('Tussionex', 'Info Tussionex'),
       ('Tysabri', 'Info Tysabri'),
       ('Tyvaso', 'Info Tyvaso'),
       ('Uloric', 'Info Uloric'),
       ('Ultiva', 'Info Ultiva'),
       ('Ultram', 'Info Ultram'),
       ('Ultrase', 'Info Ultrase'),
       ('Ultravate', 'Info Ultravate'),
       ('Unasyn', 'Info Unasyn'),
       ('Urex', 'Info Urex'),
       ('Ursodiol', 'Info Ursodiol'),
       ('Vagistat-1', 'Info Vagistat-1'),
       ('Valacyclovir Hydrochloride', 'Info Valacyclovir Hydrochloride'),
       ('Valganciclovir Hcl', 'Info Valganciclovir Hcl'),
       ('Valium', 'Info Valium'),
       ('Valproic Acid', 'Info Valproic Acid'),
       ('Valsartan and Hydrochlorothiazide', 'Info Valsartan and Hydrochlorothiazide'),
       ('Vancomycin Hydrochloride', 'Info Vancomycin Hydrochloride'),
       ('Vaprisol', 'Info Vaprisol'),
       ('Vasocidin', 'Info Vasocidin'),
       ('Vasotec', 'Info Vasotec'),
       ('Vasovist', 'Info Vasovist'),
       ('Vectibix', 'Info Vectibix'),
       ('Vectical', 'Info Vectical'),
       ('Velosulin', 'Info Velosulin'),
       ('Veltin', 'Info Veltin'),
       ('Venlafaxine Hydrochloride', 'Info Venlafaxine Hydrochloride'),
       ('Veramyst', 'Info Veramyst'),
       ('Vermox', 'Info Vermox'),
       ('Vesanoid', 'Info Vesanoid'),
       ('VESIcare', 'Info VESIcare'),
       ('Vibramycin', 'Info Vibramycin'),
       ('Vicodin', 'Info Vicodin'),
       ('Vicodin HP', 'Info Vicodin HP'),
       ('Vicoprofen', 'Info Vicoprofen'),
       ('Victoza', 'Info Victoza'),
       ('Vimovo', 'Info Vimovo'),
       ('Vimpat', 'Info Vimpat'),
       ('Vinblastine Sulfate', 'Info Vinblastine Sulfate'),
       ('Viokase', 'Info Viokase'),
       ('Vioxx', 'Info Vioxx'),
       ('Viread', 'Info Viread'),
       ('VisionBlue', 'Info VisionBlue'),
       ('Vistide', 'Info Vistide'),
       ('Vitamin K1', 'Info Vitamin K1'),
       ('Vivactil', 'Info Vivactil'),
       ('Vivelle-Dot', 'Info Vivelle-Dot'),
       ('Vusion', 'Info Vusion'),
       ('Vytorin', 'Info Vytorin'),
       ('Winstrol', 'Info Winstrol'),
       ('Xigris', 'Info Xigris'),
       ('Xolair', 'Info Xolair'),
       ('Yellow Fever Vaccine', 'Info Yellow Fever Vaccine'),
       ('Zaditor', 'Info Zaditor'),
       ('Zalcitabine', 'Info Zalcitabine'),
       ('Zanosar', 'Info Zanosar'),
       ('Zelnorm', 'Info Zelnorm'),
       ('Zemaira', 'Info Zemaira'),
       ('Zemplar', 'Info Zemplar'),
       ('Zestoretic', 'Info Zestoretic'),
       ('Zestril', 'Info Zestril'),
       ('Ziconotide', 'Info Ziconotide'),
       ('Zingo', 'Info Zingo'),
       ('Zmax', 'Info Zmax'),
       ('Zocor', 'Info Zocor'),
       ('Zolinza', 'Info Zolinza'),
       ('Zolmitriptan', 'Info Zolmitriptan'),
       ('Zonalon', 'Info Zonalon'),
       ('Zoster Vaccine Live', 'Info Zoster Vaccine Live'),
       ('Zosyn', 'Info Zosyn'),
       ('Zyclara', 'Info Zyclara'),
       ('Zyflo', 'Info Zyflo'),
       ('Zylet', 'Info Zylet'),
       ('Zyloprim', 'Info Zyloprim'),
       ('Zymaxid', 'Info Zymaxid');