/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HsPrescription extends TableImpl<Record> {

    private static final long serialVersionUID = -1515502772;

    /**
     * The reference instance of <code>public.hs_prescription</code>
     */
    public static final HsPrescription HS_PRESCRIPTION = new HsPrescription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.hs_prescription.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.hs_prescription.exam</code>.
     */
    public final TableField<Record, Long> EXAM = createField(DSL.name("exam"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.hs_prescription</code> table reference
     */
    public HsPrescription() {
        this(DSL.name("hs_prescription"), null);
    }

    /**
     * Create an aliased <code>public.hs_prescription</code> table reference
     */
    public HsPrescription(String alias) {
        this(DSL.name(alias), HS_PRESCRIPTION);
    }

    /**
     * Create an aliased <code>public.hs_prescription</code> table reference
     */
    public HsPrescription(Name alias) {
        this(alias, HS_PRESCRIPTION);
    }

    private HsPrescription(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private HsPrescription(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HsPrescription(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, HS_PRESCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HS_PRESCRIPTION_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.HS_PRESCRIPTION_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.HS_PRESCRIPTION_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.HS_PRESCRIPTION__HS_PRESCRIPTION_PRESCRIPTION_FKEY, Keys.HS_PRESCRIPTION__HS_PRESCRIPTION_EXAM_FKEY);
    }

    public Prescription prescription() {
        return new Prescription(this, Keys.HS_PRESCRIPTION__HS_PRESCRIPTION_PRESCRIPTION_FKEY);
    }

    public HsExam hsExam() {
        return new HsExam(this, Keys.HS_PRESCRIPTION__HS_PRESCRIPTION_EXAM_FKEY);
    }

    @Override
    public HsPrescription as(String alias) {
        return new HsPrescription(DSL.name(alias), this);
    }

    @Override
    public HsPrescription as(Name alias) {
        return new HsPrescription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HsPrescription rename(String name) {
        return new HsPrescription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HsPrescription rename(Name name) {
        return new HsPrescription(name, null);
    }
}
