/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HsReport extends TableImpl<Record> {

    private static final long serialVersionUID = 163984767;

    /**
     * The reference instance of <code>public.hs_report</code>
     */
    public static final HsReport HS_REPORT = new HsReport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.hs_report.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.hs_report.doctor</code>.
     */
    public final TableField<Record, Long> DOCTOR = createField(DSL.name("doctor"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.hs_report.date</code>.
     */
    public final TableField<Record, OffsetDateTime> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.hs_report.note</code>.
     */
    public final TableField<Record, String> NOTE = createField(DSL.name("note"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.hs_report</code> table reference
     */
    public HsReport() {
        this(DSL.name("hs_report"), null);
    }

    /**
     * Create an aliased <code>public.hs_report</code> table reference
     */
    public HsReport(String alias) {
        this(DSL.name(alias), HS_REPORT);
    }

    /**
     * Create an aliased <code>public.hs_report</code> table reference
     */
    public HsReport(Name alias) {
        this(alias, HS_REPORT);
    }

    private HsReport(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private HsReport(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> HsReport(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, HS_REPORT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HS_REPORT_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.HS_REPORT_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.HS_REPORT_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.HS_REPORT__HS_REPORT_PRESCRIPTION_FKEY, Keys.HS_REPORT__HS_REPORT_DOCTOR_FKEY);
    }

    public PrHsExam prHsExam() {
        return new PrHsExam(this, Keys.HS_REPORT__HS_REPORT_PRESCRIPTION_FKEY);
    }

    public HsDoctor hsDoctor() {
        return new HsDoctor(this, Keys.HS_REPORT__HS_REPORT_DOCTOR_FKEY);
    }

    @Override
    public HsReport as(String alias) {
        return new HsReport(DSL.name(alias), this);
    }

    @Override
    public HsReport as(Name alias) {
        return new HsReport(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HsReport rename(String name) {
        return new HsReport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HsReport rename(Name name) {
        return new HsReport(name, null);
    }
}
