/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicinePrescription extends TableImpl<Record> {

    private static final long serialVersionUID = -693044391;

    /**
     * The reference instance of <code>public.medicine_prescription</code>
     */
    public static final MedicinePrescription MEDICINE_PRESCRIPTION = new MedicinePrescription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.medicine_prescription.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.medicine_prescription.medicine</code>.
     */
    public final TableField<Record, Long> MEDICINE = createField(DSL.name("medicine"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.medicine_prescription.quantity</code>.
     */
    public final TableField<Record, Integer> QUANTITY = createField(DSL.name("quantity"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.medicine_prescription</code> table reference
     */
    public MedicinePrescription() {
        this(DSL.name("medicine_prescription"), null);
    }

    /**
     * Create an aliased <code>public.medicine_prescription</code> table reference
     */
    public MedicinePrescription(String alias) {
        this(DSL.name(alias), MEDICINE_PRESCRIPTION);
    }

    /**
     * Create an aliased <code>public.medicine_prescription</code> table reference
     */
    public MedicinePrescription(Name alias) {
        this(alias, MEDICINE_PRESCRIPTION);
    }

    private MedicinePrescription(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MedicinePrescription(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MedicinePrescription(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MEDICINE_PRESCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEDICINE_PRESCRIPTION_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.MEDICINE_PRESCRIPTION_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.MEDICINE_PRESCRIPTION_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.MEDICINE_PRESCRIPTION__MEDICINE_PRESCRIPTION_PRESCRIPTION_FKEY, Keys.MEDICINE_PRESCRIPTION__MEDICINE_PRESCRIPTION_MEDICINE_FKEY);
    }

    public Prescription prescription() {
        return new Prescription(this, Keys.MEDICINE_PRESCRIPTION__MEDICINE_PRESCRIPTION_PRESCRIPTION_FKEY);
    }

    public Medicine medicine() {
        return new Medicine(this, Keys.MEDICINE_PRESCRIPTION__MEDICINE_PRESCRIPTION_MEDICINE_FKEY);
    }

    @Override
    public MedicinePrescription as(String alias) {
        return new MedicinePrescription(DSL.name(alias), this);
    }

    @Override
    public MedicinePrescription as(Name alias) {
        return new MedicinePrescription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicinePrescription rename(String name) {
        return new MedicinePrescription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicinePrescription rename(Name name) {
        return new MedicinePrescription(name, null);
    }
}
