/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Medicine extends TableImpl<Record> {

    private static final long serialVersionUID = 1539285281;

    /**
     * The reference instance of <code>public.medicine</code>
     */
    public static final Medicine MEDICINE = new Medicine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.medicine.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('medicine_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.medicine.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.medicine.info</code>.
     */
    public final TableField<Record, String> INFO = createField(DSL.name("info"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.medicine</code> table reference
     */
    public Medicine() {
        this(DSL.name("medicine"), null);
    }

    /**
     * Create an aliased <code>public.medicine</code> table reference
     */
    public Medicine(String alias) {
        this(DSL.name(alias), MEDICINE);
    }

    /**
     * Create an aliased <code>public.medicine</code> table reference
     */
    public Medicine(Name alias) {
        this(alias, MEDICINE);
    }

    private Medicine(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Medicine(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Medicine(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MEDICINE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEDICINE_NAME_KEY, Indexes.MEDICINE_PKEY);
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_MEDICINE;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.MEDICINE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.MEDICINE_PKEY, Keys.MEDICINE_NAME_KEY);
    }

    @Override
    public Medicine as(String alias) {
        return new Medicine(DSL.name(alias), this);
    }

    @Override
    public Medicine as(Name alias) {
        return new Medicine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Medicine rename(String name) {
        return new Medicine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Medicine rename(Name name) {
        return new Medicine(name, null);
    }
}
