/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineTicket extends TableImpl<Record> {

    private static final long serialVersionUID = 1372249698;

    /**
     * The reference instance of <code>public.medicine_ticket</code>
     */
    public static final MedicineTicket MEDICINE_TICKET = new MedicineTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.medicine_ticket.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.medicine_ticket.date</code>.
     */
    public final TableField<Record, OffsetDateTime> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.medicine_ticket.amount</code>.
     */
    public final TableField<Record, BigDecimal> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.NUMERIC(9, 2).nullable(false), this, "");

    /**
     * Create a <code>public.medicine_ticket</code> table reference
     */
    public MedicineTicket() {
        this(DSL.name("medicine_ticket"), null);
    }

    /**
     * Create an aliased <code>public.medicine_ticket</code> table reference
     */
    public MedicineTicket(String alias) {
        this(DSL.name(alias), MEDICINE_TICKET);
    }

    /**
     * Create an aliased <code>public.medicine_ticket</code> table reference
     */
    public MedicineTicket(Name alias) {
        this(alias, MEDICINE_TICKET);
    }

    private MedicineTicket(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MedicineTicket(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MedicineTicket(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MEDICINE_TICKET);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEDICINE_TICKET_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.MEDICINE_TICKET_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.MEDICINE_TICKET_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.MEDICINE_TICKET__MEDICINE_TICKET_PRESCRIPTION_FKEY);
    }

    public MedicinePrescription medicinePrescription() {
        return new MedicinePrescription(this, Keys.MEDICINE_TICKET__MEDICINE_TICKET_PRESCRIPTION_FKEY);
    }

    @Override
    public MedicineTicket as(String alias) {
        return new MedicineTicket(DSL.name(alias), this);
    }

    @Override
    public MedicineTicket as(Name alias) {
        return new MedicineTicket(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicineTicket rename(String name) {
        return new MedicineTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedicineTicket rename(Name name) {
        return new MedicineTicket(name, null);
    }
}
