/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrHsExam extends TableImpl<Record> {

    private static final long serialVersionUID = -316000673;

    /**
     * The reference instance of <code>public.pr_hs_exam</code>
     */
    public static final PrHsExam PR_HS_EXAM = new PrHsExam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.pr_hs_exam.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pr_hs_exam.exam</code>.
     */
    public final TableField<Record, Long> EXAM = createField(DSL.name("exam"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.pr_hs_exam</code> table reference
     */
    public PrHsExam() {
        this(DSL.name("pr_hs_exam"), null);
    }

    /**
     * Create an aliased <code>public.pr_hs_exam</code> table reference
     */
    public PrHsExam(String alias) {
        this(DSL.name(alias), PR_HS_EXAM);
    }

    /**
     * Create an aliased <code>public.pr_hs_exam</code> table reference
     */
    public PrHsExam(Name alias) {
        this(alias, PR_HS_EXAM);
    }

    private PrHsExam(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PrHsExam(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PrHsExam(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, PR_HS_EXAM);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PR_HS_EXAM_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PR_HS_EXAM_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PR_HS_EXAM_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.PR_HS_EXAM__PR_HS_EXAM_PRESCRIPTION_FKEY, Keys.PR_HS_EXAM__PR_HS_EXAM_EXAM_FKEY);
    }

    public Prescription prescription() {
        return new Prescription(this, Keys.PR_HS_EXAM__PR_HS_EXAM_PRESCRIPTION_FKEY);
    }

    public HsExam hsExam() {
        return new HsExam(this, Keys.PR_HS_EXAM__PR_HS_EXAM_EXAM_FKEY);
    }

    @Override
    public PrHsExam as(String alias) {
        return new PrHsExam(DSL.name(alias), this);
    }

    @Override
    public PrHsExam as(Name alias) {
        return new PrHsExam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PrHsExam rename(String name) {
        return new PrHsExam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PrHsExam rename(Name name) {
        return new PrHsExam(name, null);
    }
}
