/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpPrescription extends TableImpl<Record> {

    private static final long serialVersionUID = -75402184;

    /**
     * The reference instance of <code>public.sp_prescription</code>
     */
    public static final SpPrescription SP_PRESCRIPTION = new SpPrescription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.sp_prescription.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sp_prescription.exam</code>.
     */
    public final TableField<Record, Long> EXAM = createField(DSL.name("exam"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.sp_prescription</code> table reference
     */
    public SpPrescription() {
        this(DSL.name("sp_prescription"), null);
    }

    /**
     * Create an aliased <code>public.sp_prescription</code> table reference
     */
    public SpPrescription(String alias) {
        this(DSL.name(alias), SP_PRESCRIPTION);
    }

    /**
     * Create an aliased <code>public.sp_prescription</code> table reference
     */
    public SpPrescription(Name alias) {
        this(alias, SP_PRESCRIPTION);
    }

    private SpPrescription(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private SpPrescription(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SpPrescription(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, SP_PRESCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SP_PRESCRIPTION_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.SP_PRESCRIPTION_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.SP_PRESCRIPTION_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.SP_PRESCRIPTION__SP_PRESCRIPTION_PRESCRIPTION_FKEY, Keys.SP_PRESCRIPTION__SP_PRESCRIPTION_EXAM_FKEY);
    }

    public Prescription prescription() {
        return new Prescription(this, Keys.SP_PRESCRIPTION__SP_PRESCRIPTION_PRESCRIPTION_FKEY);
    }

    public SpExam spExam() {
        return new SpExam(this, Keys.SP_PRESCRIPTION__SP_PRESCRIPTION_EXAM_FKEY);
    }

    @Override
    public SpPrescription as(String alias) {
        return new SpPrescription(DSL.name(alias), this);
    }

    @Override
    public SpPrescription as(Name alias) {
        return new SpPrescription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpPrescription rename(String name) {
        return new SpPrescription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpPrescription rename(Name name) {
        return new SpPrescription(name, null);
    }
}
