/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistence.jdbc.jooq.tables;


import dunder.mifflin.persistence.jdbc.jooq.Indexes;
import dunder.mifflin.persistence.jdbc.jooq.Keys;
import dunder.mifflin.persistence.jdbc.jooq.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpTicket extends TableImpl<Record> {

    private static final long serialVersionUID = 455648002;

    /**
     * The reference instance of <code>public.sp_ticket</code>
     */
    public static final SpTicket SP_TICKET = new SpTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.sp_ticket.prescription</code>.
     */
    public final TableField<Record, Long> PRESCRIPTION = createField(DSL.name("prescription"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sp_ticket.responsible</code>.
     */
    public final TableField<Record, Long> RESPONSIBLE = createField(DSL.name("responsible"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sp_ticket.date</code>.
     */
    public final TableField<Record, OffsetDateTime> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.sp_ticket.amount</code>.
     */
    public final TableField<Record, BigDecimal> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.NUMERIC(9, 2).nullable(false), this, "");

    /**
     * Create a <code>public.sp_ticket</code> table reference
     */
    public SpTicket() {
        this(DSL.name("sp_ticket"), null);
    }

    /**
     * Create an aliased <code>public.sp_ticket</code> table reference
     */
    public SpTicket(String alias) {
        this(DSL.name(alias), SP_TICKET);
    }

    /**
     * Create an aliased <code>public.sp_ticket</code> table reference
     */
    public SpTicket(Name alias) {
        this(alias, SP_TICKET);
    }

    private SpTicket(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private SpTicket(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SpTicket(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, SP_TICKET);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SP_TICKET_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.SP_TICKET_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.SP_TICKET_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.SP_TICKET__SP_TICKET_PRESCRIPTION_FKEY, Keys.SP_TICKET__SP_TICKET_RESPONSIBLE_FKEY);
    }

    public SpPrescription spPrescription() {
        return new SpPrescription(this, Keys.SP_TICKET__SP_TICKET_PRESCRIPTION_FKEY);
    }

    public Specialist specialist() {
        return new Specialist(this, Keys.SP_TICKET__SP_TICKET_RESPONSIBLE_FKEY);
    }

    @Override
    public SpTicket as(String alias) {
        return new SpTicket(DSL.name(alias), this);
    }

    @Override
    public SpTicket as(Name alias) {
        return new SpTicket(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpTicket rename(String name) {
        return new SpTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpTicket rename(Name name) {
        return new SpTicket(name, null);
    }
}
