/*
 * This file is generated by jOOQ.
 */
package dunder.mifflin.persistance.jdbc.jooq;


import dunder.mifflin.persistance.jdbc.jooq.tables.Avatar;
import dunder.mifflin.persistance.jdbc.jooq.tables.City;
import dunder.mifflin.persistance.jdbc.jooq.tables.Examination;
import dunder.mifflin.persistance.jdbc.jooq.tables.Follows;
import dunder.mifflin.persistance.jdbc.jooq.tables.General;
import dunder.mifflin.persistance.jdbc.jooq.tables.HsAdmin;
import dunder.mifflin.persistance.jdbc.jooq.tables.HsDoctor;
import dunder.mifflin.persistance.jdbc.jooq.tables.HsExam;
import dunder.mifflin.persistance.jdbc.jooq.tables.HsQualification;
import dunder.mifflin.persistance.jdbc.jooq.tables.HsReport;
import dunder.mifflin.persistance.jdbc.jooq.tables.Medicine;
import dunder.mifflin.persistance.jdbc.jooq.tables.Person;
import dunder.mifflin.persistance.jdbc.jooq.tables.PrHsExam;
import dunder.mifflin.persistance.jdbc.jooq.tables.PrMedicine;
import dunder.mifflin.persistance.jdbc.jooq.tables.PrSpExam;
import dunder.mifflin.persistance.jdbc.jooq.tables.Prescription;
import dunder.mifflin.persistance.jdbc.jooq.tables.Province;
import dunder.mifflin.persistance.jdbc.jooq.tables.Region;
import dunder.mifflin.persistance.jdbc.jooq.tables.SpExam;
import dunder.mifflin.persistance.jdbc.jooq.tables.SpQualification;
import dunder.mifflin.persistance.jdbc.jooq.tables.SpReport;
import dunder.mifflin.persistance.jdbc.jooq.tables.Specialist;
import dunder.mifflin.persistance.jdbc.jooq.tables.Ticket;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AVATAR_PKEY = Indexes0.AVATAR_PKEY;
    public static final Index AVATAR_URL_KEY = Indexes0.AVATAR_URL_KEY;
    public static final Index CITY_PKEY = Indexes0.CITY_PKEY;
    public static final Index EXAMINATION_NAME_KEY = Indexes0.EXAMINATION_NAME_KEY;
    public static final Index EXAMINATION_PKEY = Indexes0.EXAMINATION_PKEY;
    public static final Index FOLLOWS_PKEY = Indexes0.FOLLOWS_PKEY;
    public static final Index FOLLOWS_SINCE_INDEX = Indexes0.FOLLOWS_SINCE_INDEX;
    public static final Index GENERAL_PKEY = Indexes0.GENERAL_PKEY;
    public static final Index HS_ADMIN_PKEY = Indexes0.HS_ADMIN_PKEY;
    public static final Index HS_DOCTOR_PKEY = Indexes0.HS_DOCTOR_PKEY;
    public static final Index HS_EXAM_PKEY = Indexes0.HS_EXAM_PKEY;
    public static final Index HS_QUALIFICATION_PKEY = Indexes0.HS_QUALIFICATION_PKEY;
    public static final Index HS_REPORT_PKEY = Indexes0.HS_REPORT_PKEY;
    public static final Index MEDICINE_NAME_KEY = Indexes0.MEDICINE_NAME_KEY;
    public static final Index MEDICINE_PKEY = Indexes0.MEDICINE_PKEY;
    public static final Index PERSON_PKEY = Indexes0.PERSON_PKEY;
    public static final Index PR_HS_EXAM_PKEY = Indexes0.PR_HS_EXAM_PKEY;
    public static final Index PR_MEDICINE_PKEY = Indexes0.PR_MEDICINE_PKEY;
    public static final Index PR_SP_EXAM_PKEY = Indexes0.PR_SP_EXAM_PKEY;
    public static final Index PRESCRIPTION_PKEY = Indexes0.PRESCRIPTION_PKEY;
    public static final Index PROVINCE_PKEY = Indexes0.PROVINCE_PKEY;
    public static final Index REGION_PKEY = Indexes0.REGION_PKEY;
    public static final Index SP_EXAM_PKEY = Indexes0.SP_EXAM_PKEY;
    public static final Index SP_QUALIFICATION_PKEY = Indexes0.SP_QUALIFICATION_PKEY;
    public static final Index SP_REPORT_PKEY = Indexes0.SP_REPORT_PKEY;
    public static final Index SPECIALIST_PKEY = Indexes0.SPECIALIST_PKEY;
    public static final Index TICKET_PKEY = Indexes0.TICKET_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AVATAR_PKEY = Internal.createIndex("avatar_pkey", Avatar.AVATAR, new OrderField[] { Avatar.AVATAR.ID }, true);
        public static Index AVATAR_URL_KEY = Internal.createIndex("avatar_url_key", Avatar.AVATAR, new OrderField[] { Avatar.AVATAR.URL }, true);
        public static Index CITY_PKEY = Internal.createIndex("city_pkey", City.CITY, new OrderField[] { City.CITY.ID }, true);
        public static Index EXAMINATION_NAME_KEY = Internal.createIndex("examination_name_key", Examination.EXAMINATION, new OrderField[] { Examination.EXAMINATION.NAME }, true);
        public static Index EXAMINATION_PKEY = Internal.createIndex("examination_pkey", Examination.EXAMINATION, new OrderField[] { Examination.EXAMINATION.ID }, true);
        public static Index FOLLOWS_PKEY = Internal.createIndex("follows_pkey", Follows.FOLLOWS, new OrderField[] { Follows.FOLLOWS.ID }, true);
        public static Index FOLLOWS_SINCE_INDEX = Internal.createIndex("follows_since_index", Follows.FOLLOWS, new OrderField[] { Follows.FOLLOWS.SINCE.desc() }, false);
        public static Index GENERAL_PKEY = Internal.createIndex("general_pkey", General.GENERAL, new OrderField[] { General.GENERAL.ID }, true);
        public static Index HS_ADMIN_PKEY = Internal.createIndex("hs_admin_pkey", HsAdmin.HS_ADMIN, new OrderField[] { HsAdmin.HS_ADMIN.ID }, true);
        public static Index HS_DOCTOR_PKEY = Internal.createIndex("hs_doctor_pkey", HsDoctor.HS_DOCTOR, new OrderField[] { HsDoctor.HS_DOCTOR.ID }, true);
        public static Index HS_EXAM_PKEY = Internal.createIndex("hs_exam_pkey", HsExam.HS_EXAM, new OrderField[] { HsExam.HS_EXAM.ID }, true);
        public static Index HS_QUALIFICATION_PKEY = Internal.createIndex("hs_qualification_pkey", HsQualification.HS_QUALIFICATION, new OrderField[] { HsQualification.HS_QUALIFICATION.DOCTOR, HsQualification.HS_QUALIFICATION.EXAM }, true);
        public static Index HS_REPORT_PKEY = Internal.createIndex("hs_report_pkey", HsReport.HS_REPORT, new OrderField[] { HsReport.HS_REPORT.PRESCRIPTION }, true);
        public static Index MEDICINE_NAME_KEY = Internal.createIndex("medicine_name_key", Medicine.MEDICINE, new OrderField[] { Medicine.MEDICINE.NAME }, true);
        public static Index MEDICINE_PKEY = Internal.createIndex("medicine_pkey", Medicine.MEDICINE, new OrderField[] { Medicine.MEDICINE.ID }, true);
        public static Index PERSON_PKEY = Internal.createIndex("person_pkey", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index PR_HS_EXAM_PKEY = Internal.createIndex("pr_hs_exam_pkey", PrHsExam.PR_HS_EXAM, new OrderField[] { PrHsExam.PR_HS_EXAM.PRESCRIPTION }, true);
        public static Index PR_MEDICINE_PKEY = Internal.createIndex("pr_medicine_pkey", PrMedicine.PR_MEDICINE, new OrderField[] { PrMedicine.PR_MEDICINE.PRESCRIPTION }, true);
        public static Index PR_SP_EXAM_PKEY = Internal.createIndex("pr_sp_exam_pkey", PrSpExam.PR_SP_EXAM, new OrderField[] { PrSpExam.PR_SP_EXAM.PRESCRIPTION }, true);
        public static Index PRESCRIPTION_PKEY = Internal.createIndex("prescription_pkey", Prescription.PRESCRIPTION, new OrderField[] { Prescription.PRESCRIPTION.ID }, true);
        public static Index PROVINCE_PKEY = Internal.createIndex("province_pkey", Province.PROVINCE, new OrderField[] { Province.PROVINCE.ID }, true);
        public static Index REGION_PKEY = Internal.createIndex("region_pkey", Region.REGION, new OrderField[] { Region.REGION.ID }, true);
        public static Index SP_EXAM_PKEY = Internal.createIndex("sp_exam_pkey", SpExam.SP_EXAM, new OrderField[] { SpExam.SP_EXAM.ID }, true);
        public static Index SP_QUALIFICATION_PKEY = Internal.createIndex("sp_qualification_pkey", SpQualification.SP_QUALIFICATION, new OrderField[] { SpQualification.SP_QUALIFICATION.SPECIALIST, SpQualification.SP_QUALIFICATION.EXAM }, true);
        public static Index SP_REPORT_PKEY = Internal.createIndex("sp_report_pkey", SpReport.SP_REPORT, new OrderField[] { SpReport.SP_REPORT.PRESCRIPTION }, true);
        public static Index SPECIALIST_PKEY = Internal.createIndex("specialist_pkey", Specialist.SPECIALIST, new OrderField[] { Specialist.SPECIALIST.ID }, true);
        public static Index TICKET_PKEY = Internal.createIndex("ticket_pkey", Ticket.TICKET, new OrderField[] { Ticket.TICKET.PRESCRIPTION }, true);
    }
}
